### ISSUE TITLE
Problem using cygwin on windowsxp

### ISSUE THREAD

**Issue by fluffy** [cisco/libsrtp#1]
http://sourceforge.net/tracker/?func=detail&aid=1812238&group_id=38894&atid=423800

version 1.4.2
i'm using cygwin on windowsxp
After configure and correct make and makeruntest.
When I try to run the test, from the receiver instance I have this error continuosly 

"error: srtp unprotection failed with code 2".

--------------------------------------------------
version downloaded from cvs.
I have the same error 
"error: srtp unprotection failed with code 2".
but now when I run makeruntest
The last lines of shell are those

CPU set to little-endian (WORDS_BIGENDIAN == 0)
CPU set to CISC (CPU_CISC == 1)
using native 64-bit type (NO_64_BIT_MATH == 0)
using stdout for error reporting (ERR_REPORTING_STDOUT == 1)
using as a random source (DEV_URANDOM == )
warning: configuration is probably in error (found 1 problems)
make[1]: *** [runtest] Error 1
make[1]: Leaving directory `/home/srtp144/crypto'
make: *** [runtest] Error 2

Could yoy help me ?
Tanks in advance
lorenzo

lorenzo.martin@tin.it

**Comment by jfigus** [comment]
I've removed all references to DEV_URANDOM in fac1f50bb2dee8d64997ec507c0514e0eb40ce80.  I don't have a mingw setup to confirm that this was the only problem with building on mingw.  Hopefully the problem is resolved now.
