### ISSUE TITLE
make libsrtp.so does not work

### ISSUE THREAD

**Issue by marius-nyxpoint** [cisco/libsrtp#100]
The libsrtp.so target has disappeared for versions > 1.5.0. How can I build an shared library for the latest version?

Sorry if I offend someone with my ignorance. After many hours of searching, the only answer I got is to pass the -fPIC flag which didn’t prove that helpful (in fact, I think it is passed by default; twice).

**Comment by jfigus** [comment]
It works for me.  Try this:

./configure
make shared_library

**Comment by jfigus** [comment]
Closing issue due to no response.

**Comment by marius-nyxpoint** [comment]
It works nicely. Thanks!

Sorry for the late response, I somehow didn't see the answer.

**Comment by traud** [comment]
Same pitfall for me. The Makefile.in (in the branch 1.5.x, 2.0.x, and master) still mentions this old target at the top, in a comment. Is that intended?
