### ISSUE TITLE
Provide a version constant in the headers

### ISSUE THREAD

**Issue by ibauersachs** [cisco/libsrtp#101]
Please add a `#define` in one of the headers the specifies the current version. This would be useful for other projects to require a minimum version (or at least issue a warning) at compile time.

For example Asterisk needs at least 1.5.0 to not run into the issue fixed with commit e896bf7b3e269ad15dfa37eb1f679c1d8c29b7ad, but cannot currently check what version of libsrtp is present on the system.

**Comment by jfigus** [comment]
This was added recently in master.  You can use SRTP_VER_STRING or SRTP_VERSION.  But you're encouraged to get this information at runtime using either srtp_get_version() or srtp_get_version_string().
