### ISSUE TITLE
Maintain branch for 1.5.x fixes

### ISSUE THREAD

**Issue by fancycode** [cisco/libsrtp#104]
As other projects (applies for example to Chrome) might still be using libsrtp 1.5.x, it would maybe be good to have a branch that can receive maintenance bugfixes. As you have merged the changes for 2.0.x to master, keeping track of such changes for 1.5.x will be complicated.

I would suggest using 945eeee980e496ecad0f7df39c8033fe18983921 as branch point.

**Comment by jfigus** [comment]
We already have a branch for releasing 1.5.x maintenance fixes.  The branch name is 1_5_x_throttle.

**Comment by fancycode** [comment]
Sorry, I somehow missed that. Thanks.
