### ISSUE TITLE
Avoid inline asm when compiling with -ansi

### ISSUE THREAD

**Issue by nrensen** [cisco/libsrtp#106]
gcc doesn't permit asm when compiling with the -ansi flag:
https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html

```
--- crypto/include/datatypes.h.orig     Mon Apr 27 10:13:48 2015
+++ crypto/include/datatypes.h  Mon Apr 27 10:14:19 2015
@@ -399,7 +399,7 @@
 # define be64_to_cpu(x)	bswap_64((x))
 #else

-#if defined(__GNUC__) && defined(HAVE_X86)
+#if defined(__GNUC__) && defined(HAVE_X86) && !defined(__STRICT_ANSI__)
 /* Fall back. */
 static inline uint32_t be32_to_cpu(uint32_t v) {
    /* optimized for x86. */
```

**Comment by JonathanLennox** [comment]
GCC should accept it if you spell it __asm__, even in -ansi mode.

On Apr 29, 2015, at 8:31 PM, nrensen <notifications@github.com<mailto:notifications@github.com>> wrote:


gcc doesn't permit asm when compiling with the -ansi flag:
https://gcc.gnu.org/onlinedocs/gcc/C-Dialect-Options.html

--- crypto/include/datatypes.h.orig     Mon Apr 27 10:13:48 2015
+++ crypto/include/datatypes.h  Mon Apr 27 10:14:19 2015
@@ -399,7 +399,7 @@
 # define be64_to_cpu(x)    bswap_64((x))
 #else

-#if defined(__GNUC__) && defined(HAVE_X86)
+#if defined(__GNUC__) && defined(HAVE_X86) && !defined(__STRICT_ANSI__)
 /* Fall back. */
 static inline uint32_t be32_to_cpu(uint32_t v) {
    /* optimized for x86. */

**Comment by jfigus** [comment]
C90 doesn't support inline.  When using -ansi, isn't that the equivalent of C90?  We'd have to eliminate the use of inline too, which is fine with me.  Modern compilers are going to inline automatically anyway.

**Comment by nrensen** [comment]
You're right. In my case C99 is ok and the simple fix of using __asm__ as suggested by @JonathanLennox works fine. Perhaps there is no value in supporting C90.

**Comment by saghul** [comment]
MSVC does not support C99 (I hear it has improved in the 2015 version, but
I haven't checked), so many people stay C90 for portability. Not sure if it
applies here though.

**Comment by jfigus** [comment]
Closing this issue until there's a larger impetus to support C90.
