### ISSUE TITLE
srtp brew package does not generate the pkgconfig file

### ISSUE THREAD

**Issue by ibc** [cisco/libsrtp#111]
Just that. Installing libsrtp in OSX via `brew install srtp` install the 1.5.2 version, but it does not expose the pkgconfig file.

Not sure if this issue is related to this project or how Homebrew handles this library.

**Comment by saghul** [comment]
If `make install` does install the pc file, then it's a Homebrew issue.

**Comment by ibc** [comment]
No idea about Brew stuff, but the brew **libuv** formula does properly installs the PKG file upon `brew install libuv` while the **srtp** formula does not.

* https://github.com/Homebrew/homebrew/blob/master/Library/Formula/libuv.rb
* https://github.com/Homebrew/homebrew/blob/master/Library/Formula/srtp.rb

**Comment by saghul** [comment]
Maybe they use a prefix, in libuv you install "libuv" and the file is "libuv.pc", whereas here you install "srtp" but the file is called "libsrtp.pc". No idea really, but I'm pretty positive it's a Homebrew issue really...

**Comment by ibc** [comment]
No. Tested that there is no *srtp*.pc within /usr/local once `brew install srtp`.

**Comment by ibc** [comment]
I've open an issue in the brew project (crossreporting): https://github.com/Homebrew/homebrew/issues/42173

**Comment by ibc** [comment]
Fixed in brew: https://github.com/Homebrew/homebrew/commit/feec2cef04b69eb2355e609eab0ff304673f633e
