### ISSUE TITLE
Complete quoting for parameters in "configure.ac"

### ISSUE THREAD

**Issue by elfring** [cisco/libsrtp#113]
I suggest to be more explicit where [macro expansion](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Autoconf-Language.html) will not be required in [the current build configuration script](https://github.com/cisco/libsrtp/blob/038d2cf305923e0c63591ff716137bf0f48e2d5d/configure.in#L56).

**Comment by jfigus** [comment]
Feel free to submit a pull request with your suggested fixes.

**Comment by elfring** [comment]
Thanks for [your improvement of the build configuration script](https://github.com/cisco/libsrtp/commit/5e67d396feeb2c834f13d685335772871ed2ec21 "proper quoting and small improvements").
