### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cisco/libsrtp#114]
I would like to point out that identifiers like "[`_AES_H`](https://github.com/cisco/libsrtp/blob/ed2212973b3248dde97849e38f3d50a752e98d41/crypto/include/aes.h#L46)" and "[`_DATATYPES_H`](https://github.com/cisco/libsrtp/blob/ed2212973b3248dde97849e38f3d50a752e98d41/crypto/include/datatypes.h#L47)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by jfigus** [comment]
Good point.  Fortunately the standard C library doesn't have aes.h or datatypes.h.  Otherwise this probably would have been an issue much earlier.  I'll leave this issue open and address this sometime in the future.
