### ISSUE TITLE
Add support for RFC 6904 encrypted header extensions

### ISSUE THREAD

**Issue by juberti** [cisco/libsrtp#124]
Extend srtp_protect/unprotect to encrypt header extensions according to RFC 6904.

The extensions to be encrypted would be set by a new API, e.g. 
srtp_set_protect_extns(srtp_t session, const int* extn_ids, int extn_ids_len);

**Comment by jfigus** [comment]
Which downstream project requires this?

**Comment by JonathanLennox** [comment]
It's required by the RTCWeb RTP usage spec, so anything that's using LibSRTP for WebRTC.

**Comment by jnoring** [comment]
https://github.com/ging/licode would be impacted, which is one of the most commonly used WebRTC media servers.

**Comment by fancycode** [comment]
This can be closed (implemented in #128).
