### ISSUE TITLE
Activate Travis

### ISSUE THREAD

**Issue by fancycode** [cisco/libsrtp#127]
There is a `travis.yml` in the repository, however it doesn't seem to be activated on Travis:
https://travis-ci.org/cisco/libsrtp

**Comment by j4y** [comment]
I got this working and sent a PR for the travis.yml, but there were some issues getting it activated because of TravisCI having read access to all of the cisco git repositories.

**Comment by fancycode** [comment]
Ah, just saw that there was more discussion on #120. Referencing this here in case other are searching for further information.

**Comment by pabuhler** [comment]
As of today this is working, see https://travis-ci.org/cisco/libsrtp, thanks @fluffy.
