### ISSUE TITLE
please remove obsolete and non-DFSG-free releases/* dir

### ISSUE THREAD

**Issue by jonassmedegaard** [cisco/libsrtp#131]
Hi,

Thanks for removing the RFC files.  Unfortunately there are still copies of those left in the releases/* tarballs.

Please consider dropping that directory, as it seems to be just dead weight (yes, also the PDF if you don't mind).

Regards,

 - Jonas

**Comment by j4y** [comment]
This was done in pull request 122 and merged:

https://github.com/cisco/libsrtp/pull/122

**Comment by jfigus** [comment]
Closing
