### ISSUE TITLE
please remove obsolete and not intended for release .cvsignore files

### ISSUE THREAD

**Issue by jonassmedegaard** [cisco/libsrtp#132]
.cvsignore files are intended for use when working from CVS checkouts only - when producing release tarballs they should be omitted, and when using git as revision control system they probably serve no purpose at all.

Please consider dropping all .cvsignore files (I don't se any in my git checkout, but several in the released tarball, so perhaps there's something fishy going on in either a custom branch used for releases or at some checkout used for preparing reeases).

 - Jonas

**Comment by j4y** [comment]
This was done in pull request 119, which has been merged.

**Comment by jfigus** [comment]
Closing this this was done in PR 119.
