### ISSUE TITLE
please consider remove PDF from source

### ISSUE THREAD

**Issue by jonassmedegaard** [cisco/libsrtp#133]
Hi,

Source git (and release tarballs) contain a PDF file doc/libsrtp.pdf.

That file seems to simply be the product of building the Doxygen build rules.

Please consider ship only source in the source tarball: PDF almost doubles the size of the tarball, and some (including Debian) dislike redistributing prebuilt stuff which is difficult to verify if having derived from its source.

 - Jonas

**Comment by jfigus** [comment]
We use Github to generate the tarball, which is primarily a convenience.  We would have to remove the PDF from the git repo.  I'm fine with this, but others may complain.  Although, the PDF is currently out-of-date and hasn't been updated in quite some time.

**Comment by jfigus** [comment]
Nobody else in the community seems to be interested in this issue.  I've gone ahead and removed the out-dated PDF in 922a8e43f995219acaaba52c0fbf5026e274a0d7.
