### ISSUE TITLE
Status of 2.X?

### ISSUE THREAD

**Issue by ibc** [cisco/libsrtp#140]
Hi, which is the status of the 2.x version? is it production/testing ready?

The API is much better and clean, with proper `SRTP_` and `srtp_` prefixes for all the exported stuff. Good work.

Just a question: does 2.x still handle SSRC globally? 1.x handles them globally, which means that the same SSRC cannot be used within different SRTP sessions (this is not cool when it comes to a SFU server architecture, in which the server relays an incoming stream to N endpoints, having to rewrite the incoming SSRC to N different values).

**Comment by jfigus** [comment]
You're probably right, it's time to release 2.0.0.  There haven't been many issues popping up on the master branch and the code has been there for quite some time.  I'll do the release in the near future.

**Comment by ibc** [comment]
May you please clarify regarding my question above (global or per session SSRC table)?

:)

**Comment by jfigus** [comment]
The SSRC is global to **srtp_ctx_t**.  The application can instantiate multiple srtp_ctx_t (a.k.a. srtp_t) if needed.  Therefore, I wouldn't conclude that SSRC is handled globally by the library.  There are currently no plans to change this hierarchy.

**Comment by ibc** [comment]
> The SSRC is global to srtp_ctx_t. The application can instantiate multiple srtp_ctx_t (a.k.a. srtp_t) if needed.

Sorry, my fault. Just a simple question:

* I create a `srtp_t` with policy `ssrc_any_inbound`.
* I receive a SRTP packet with ssrc `1234` and unprotect it.
  * Here I assume that a new `srtp_stream_t` is created with ssrc `1234` within the `srtp_t` session.
* Later I call `srtp_remove_stream(session, 1234)`.

Will the latest call remove the internally created `srtp_stream_t` session so I can start receiving again packets with ssrc `1234` with a 100% reseted stream and sequence numbers?

Thanks a lot.

**Comment by ibc** [comment]
> Therefore, I wouldn't conclude that SSRC is handled globally by the library. There are currently no plans to change this hierarchy.

And I hope such a hierarchy is never changed :)

**Comment by jfigus** [comment]
In theory you're proposal should work.  I've never tested this exact flow myself.  But assuming you have the stream template setup right, it should work.

**Comment by jfigus** [comment]
2.0.0 has been released.

**Comment by ibc** [comment]
Thanks!

**Comment by ukreator** [comment]
@ibc make sure you call srtp_remove_stream(session, **htonl(1234)**). See #105 for details

**Comment by ibc** [comment]
Thanks a lot @ukreator
