### ISSUE TITLE
stdint.h usage (uint32_t, etc)

### ISSUE THREAD

**Issue by ibc** [cisco/libsrtp#141]
```c
typedef struct { 
  srtp_ssrc_type_t type;  /**< The type of this particular SSRC */
  unsigned int     value; /**< The value of this SSRC, if it is not a wildcard */
} srtp_ssrc_t;
```

Ok, in any current arch `unsigned int` holds at least 4 bytes, but why doesn't libsrtp use `uint32_t` defined in stdint.h?

**Comment by jfigus** [comment]
Int is used in the struct you pasted in the issue, not uint32_t.  Which occurrence of uint32_t are you referring too?  In many places uint32_t is used to guarantee only 32 bits of memory are used.  Some architectures use 64-bits for int.

**Comment by ibc** [comment]
For example:

```c
typedef struct srtp_crypto_policy_t {
  srtp_cipher_type_id_t cipher_type;    /**< An integer representing
				         *   the type of cipher.  */
  int              cipher_key_len; /**< The length of the cipher key
				    *   in octets.                       */
  srtp_auth_type_id_t   auth_type;      /**< An integer representing the
				         *   authentication function.         */
  int              auth_key_len;   /**< The length of the authentication 
				    *   function key in octets.          */
  int              auth_tag_len;   /**< The length of the authentication 
				    *   tag in octets.                   */
  srtp_sec_serv_t  sec_serv;       /**< The flag indicating the security
				    *   services to be applied.          */
} srtp_crypto_policy_t;
```

I expect that `unit32_t` would be better than `int` there (there are more similar cases).

**Comment by jfigus** [comment]
I can't argue that int is providing more storage than needed for auth_key_len, auth_tag_len, and many others. But there's no harm in this other than wasting a little memory.  I wouldn't classify the current design of these structs as atrocious.

**Comment by ibc** [comment]
It's fine. It is just that I love fixed length fields :)
