### ISSUE TITLE
[2.0] error in srtp_create() documentation

### ISSUE THREAD

**Issue by ibc** [cisco/libsrtp#142]
In https://github.com/cisco/libsrtp/blob/2_0_0_dev/include/srtp.h#L557:

Signature of the function is:

```c
srtp_err_status_t srtp_create(srtp_t *session, const srtp_policy_t *policy);
```

But the built-in doc says:

> 
 * The function call srtp_create(session, policy, key) allocates and
 * initializes an SRTP session context, applying the given policy and
 * key.

...but there is no `key` argument.

**Comment by jfigus** [comment]
Resolved by 92c3de37fcbb16f8dcfba81dbdace2e5520d1c52
