### ISSUE TITLE
srtp_policy_t *policy in srtp_add_stream()

### ISSUE THREAD

**Issue by ibc** [cisco/libsrtp#143]
```c
srtp_err_status_t srtp_add_stream(srtp_t session, const srtp_policy_t *policy);
```

* Is the given `policy` appended (as last element) in the existing list of `srtp_polity_t` of the `srtp_t` session?

* Must the given `policy` have `next = NULL`?

* Can the given `policy` have a `next` value pointing to another `srtp_policy_t` struct? or must it be a single policy?

**Comment by jfigus** [comment]
**srtp_t** doesn't have a policy member.  The policy list is provided when invoking **srtp_create()** . The **next** member may point to another policy.  It's a linked list.  If there are multiple policies in the list, **srtp_create()** will create a new stream for each policy.

The **next** member is not used when passing a policy to **srtp_add_stream()**.  If you pass a linked list of policies to **srtp_add_stream()**, only the first policy will be used to create the stream.

**Comment by ibc** [comment]
Clear. Thanks.
