### ISSUE TITLE
[2.0] Wrong doc for srtp_event_t

### ISSUE THREAD

**Issue by ibc** [cisco/libsrtp#144]
In https://github.com/cisco/libsrtp/blob/2_0_0_dev/include/srtp.h#L1332

>
When a key expires or the maximum number of packets has been
reached, an SRTP stream will enter an `expired' state in which no
more packets can be protected or unprotected.  When this happens,
it is likely that you will want to either deallocate the stream
(using srtp_stream_dealloc()

but there is no `srtp_stream_dealloc()`. I assume it means `srtp_remove_stream()`.

**Comment by jfigus** [comment]
Resolved by 92c3de37fcbb16f8dcfba81dbdace2e5520d1c52
