### ISSUE TITLE
Update defines in configure

### ISSUE THREAD

**Issue by ibc** [cisco/libsrtp#152]
In https://github.com/cisco/libsrtp/blob/master/configure#L580:

```
PACKAGE_NAME='libsrtp2'
PACKAGE_TARNAME='libsrtp2'
PACKAGE_VERSION='2.0.0-pre'
PACKAGE_STRING='libsrtp2 2.0.0-pre'
```

Shouldn't it be `2.0.0` to be in sync with the Git release tag?

**Comment by pabuhler** [comment]
master should always include the "-pre" to indicate that it is not a release, but it should also be pointing at the next minor version, so in this case 2.1.0-pre .
Commit ef139ef has already bump the version to 2.0.1-pre on the 2_0_x_throttle branch .
