### ISSUE TITLE
config.guess and config.sub are old

### ISSUE THREAD

**Issue by JonathanLennox** [cisco/libsrtp#159]
The config.guess and config.sub files in libsrtp are old, which means (among other things) that they don't support arm64 (necessary for current Android and iOS).  Anyone mind if I update them? (I think I have commit privileges still.)

**Comment by paulej** [comment]
No objection from me

**Comment by JonathanLennox** [comment]
Okay, I've pushed them to both master and the 1_5_x_throttle branch.

**Comment by JonathanLennox** [comment]
Also applied to 2_0_x_throttle, which I'd overlooked.
