### ISSUE TITLE
update docs to replace crypto_get_random

### ISSUE THREAD

**Issue by traud** [cisco/libsrtp#161]
Since 4494760, the symbol `crypto_get_random` was moved to the private headers. I know that this symbol was removed in the 2.0.x branch completely. And the libSRTP maintainers do not want us to use libSRTP as Random Number Generator (RNG) anymore. And to work around this issue, is [quite easy](https://issues.asterisk.org/jira/browse/ASTERISK-24436). OK. However, this breaks API compatibility between 1.5.x and the former 1.4.x branches.
A) Was that move intended as a wake-up call or
B) just a look-over because the commit message did not indicate that consequence?

Furthermore, [doc/intro.txt](https://github.com/cisco/libsrtp/blob/master/doc/intro.txt) still mentions `crypto_get_random` in its example code—in all branches—which might confuse new users. In that intro, what about mentioning that `key` should be a random number. To achieve this, for example `RAND_bytes(key, 30)` of [OpenSSL](https://www.openssl.org/docs/manmaster/crypto/RAND_bytes.html) can be used.

**Comment by jfigus** [comment]
The old libsrtp RNG wasn't deemed secure.  It was removed to prevent users from using it, and thus shooting themselves in the foot.

Agreed, the docs are grossly out of date.  They haven't been updated in years.  If you're volunteering to update them, please submit a PR.

**Comment by traud** [comment]
Yes, I understand why it was removed in the 2.0.x branch. However, from your answer I did not understand whether this is it the same situation for the 1.5.x branch. The current code requires downstream projects to be patched. If that was intended: Many projects just include that private header file, instead of using an alternative RNG. So, if that was intended even for the 1.5.x branch, I wonder if it is possible to improve the ‘documentation’ like using a deprecation pragma/define instead of moving the symbol.

**Comment by jfigus** [comment]
Given 1.4->1.5 was a minor release revision, it's debatable whether API compatibility is a requirement.  I'm not sure there's an API/ABI compatibility policy set for the libsrtp project.  To avoid this in the future, we should probably define a policy and follow it.  I do know that other projects, such as OpenSSL, are only API compatible between micro releases.  

The intention *was* to remove the RNG.  Using it was not considered safe.  Using poor random sources is a known vulnerability.  Many examples of this have been shown by the academic community.  We're trying to keep people from shooting themselves in the foot.  

Having been in the software security field for the past 5 years, the dilemma of forced deprecation is a repeating theme.  Yes, there is pain with deprecating old ciphers.  Downstream developers will complain when they have to update their code.  However, there are a lot of downstream developers that would *not* update their code if deprecation didn't occur.  We've seen this time & time again with various ciphers.  So the question is do we deprecate the API and force the hand of downstream developers, or retain the insecure cipher and hope down-streamers will deprecate insecure ciphers themselves.  My experience has been that unless the down-streamer is someone that works with security related software, they don't understand the risks and often neglect to deprecate insecure ciphers.

**Comment by traud** [comment]
Mhm. Do not get me wrong, please. I am very happy about that change because it pointed out an issue which would not have passed in a security audit. Because of that change, I stumbled over that issue and avoided a test failure because of an unmaintained random number generator.

However, back to my initial question:
Was this change intended on the 1.5.x branch as well?

**Comment by jfigus** [comment]
Yes, the intention was to remove the RNG in 1.5.x.

**Comment by traud** [comment]
OK. In that case, why were the commits
- 339b61d
- 2569049
- fb83841
- fac1f50

not backported to the 1.5.x branch? I am asking, because some downstream projects changed just the included header files instead of looking for a replacement RNG. With those commits, one would have been *forced* to go for another RNG.

**Comment by jfigus** [comment]
Sorry for the confusion, but crypto_get_random() was only used by the unit tests, which was removed in 1.5.x.  The full deprecation of the RNG was done in 2.0.x.  If I recall, this was essentially dead code cleanup.

**Comment by traud** [comment]
Please, do not feel sorry. I just want to understand this and learn from this issue here. OK, after reading and reading this again, do you mean: `crypto_get_random(.)` should have _never_ been used by downstream projects, even before version 1.5.x – although it was mentioned in the documentation and was a public method? `crypto_get_random(.)` was just created/used internally not to rely on further external libraries. Is that the correct understanding of your last comment? That is OK for me, I just want to understand the rationale and what exactly led to this confusion (the initial documentation from the year 2003, that recent change, or its commit message).

> debatable whether API compatibility is a requirement. I'm not sure there's an API/ABI compatibility policy set for the libsrtp project

Mhm. I am quite new to libraries, but aren’t there exiting rules like the [SONAME](https://autotools.io/libtool/version.html)?

> The full deprecation of the RNG was done in 2.0.x. If I recall, this was essentially dead code cleanup.

Now, I am sorry because after re-reading this so often, I still do not get that: What do you mean by _full_ (or to be more precise by _partial_) – why wasn’t this done for the branch `1_5_x_throttle`? In 1.5.x, this part of the code was not dead yet, therefore it remained included (but moved). Is that the correct understanding?

**Comment by pabuhler** [comment]
Hi, I would like to get a conclusion on this issue and it is a little difficult to figure out. @traud at this point is there still any definite changes you would like to see? Keeping in mind that we really do not want to release  an new 1.5 version unless there is a major security problem.

**Comment by traud** [comment]
I am quite good in explaining things and I invested a bit amount of time in this report. Therefore, if you are not able to understand this report, please, ask in detail your questions. If possible, add two or one interpretations you cannot decide between to each of your questions. When you have understood this, we can discuss about definite changes for the various branches.

It is a pity, John stepped out of answering my questions. That would have helped to understand the root cause.

**Comment by pabuhler** [comment]
So going back to your original post, the documentation should definitely be updated, it is not just the mention of crypto_get_random that is out of date. This will be updated for the next release , version 2.1.

With regard to the 1.5 branch , I can agree that the documentation is out of date but  I am reluctant to spend time fixing up the documentation there, perhaps once it is updated in master can consider back porting.

I am unable to answer with regard to the intention of the changes in the 1.5 branch, as you say it is a pity John was not able to clarify this for you.

At some point you seamed to suggest re adding the symbol to 1.5 but with a deprecation pragma/define, is  that something you would still like to see?

**Comment by pabuhler** [comment]
The docs have now been changed to use a static key.
