### ISSUE TITLE
Webpages: download latest/current

### ISSUE THREAD

**Issue by traud** [cisco/libsrtp#162]
1.4.2 http://srtp.sourceforge.net/download.html
1.4.4 http://sourceforge.net/projects/srtp/files/
2.0.0 http://github.com/cisco/libsrtp/releases/
Although the latest libSRTP 1.x compatible version is [1.5.4](http://github.com/cisco/libsrtp/tags), currently. Therefore, is it possible:
- get one static URL which points the current release of the 1.x branch?
- update all webpages at Sourceforge to point to that link?

The libSRTP tarballs are referenced in a lot of scripts and guides. Having a `libsrtp1-current.tgz` might reduce the amount of downloads on Sourceforge. Not sure about the statistics of version 1.4.2 and version 1.5.4. Anyway, 160 downloads per week for 1.4.4 sound high to me – on an outdated version. I fear a lot of users miss the GitHub repository and the release(s) here. Would be a shame, especially because of the new OpenSSL features of 1.5.x (AES-GCM, AES-IN).

Same for news:
http://srtp.sourceforge.net/news.html
http://sourceforge.net/p/srtp/news/
Can’t those two webpages point to
http://github.com/cisco/libsrtp/tags

**Comment by jfigus** [comment]
This is a good idea to deprecate the download link on Sourceforge, and I would offer to help if I had access to the Sourceforge project.  Maybe one of the legacy SRTP maintainers can help out here.

**Comment by traud** [comment]
Yes, beside Sourceforge it would help to have one static link on GitHub itself, where to download the latest 1.x compatible tgz file. That way, scripts and guides which do not depend on a special version could always fetch the latest version. Therefore, I am about a tgz to stay compatible with the previous download files. I digged a bit around in the GitHub help files but did not find anything for that – which confuses me a bit because this should be handy for all security related projects. Perhaps it is possible to create a special release tag. No idea. If you do not find anything either, I go for a fork and play a bit around what is possible.

**Comment by jfigus** [comment]
You may be able to use the following link to get the latest on the 1.5.x throttle branch at any time:
https://github.com/cisco/libsrtp/archive/1_5_x_throttle.zip

**Comment by traud** [comment]
Yes, I am using that and I am quite happy with that. Actually, I am using
https://github.com/cisco/libsrtp/archive/1_5_x_throttle.tar.gz
to stay compatible to older guides/scripts which expected a `tgz` file.

However, before I posted this issue, I read a message from you, that downstream projects should use just releases. Throttle are the release branches. Were you about ‘release branches’ or about ‘released versions’?

**Comment by pabuhler** [comment]
We have added release tags for Major/Minor/Patch so now it is possible to have a static link to most recent stable release of your choice. See https://github.com/cisco/libsrtp/wiki#releases .
So for example if you always wanted the most stable 1.5 release regardless on patch you could use https://github.com/cisco/libsrtp/archive/v1.5.tar.gz .

We are attempting to update the older source forge pages to point to gitgub.

**Comment by pabuhler** [comment]
https://sourceforge.net/projects/srtp/ and http://srtp.sourceforge.net have both been updated to point to https://github.com/cisco/libsrtp where possible.
