### ISSUE TITLE
Does this library work well for iOS?

### ISSUE THREAD

**Issue by sahara108** [cisco/libsrtp#168]
Is there anybody use this library for iOS. I am using this configuration to build the library
`
CFLAGS="${BITCODE} -isysroot ${SDK} -Wno-error -Wno-implicit-function-declaration ${EXTRAS} -O0 -g -Wall"
	
	./configure --prefix="${CURRENT}/autobuild-${ARCH}" CC="${CLANG} ${CFLAGS}"  CPP="${CLANG} -E"  CPPFLAGS="${CFLAGS}" \
	--host=aarch64-apple-darwin --disable-assembly --enable-static --disable-shared ${ARGS} \ --disable-debug --disable-stdout
`

but it seems that the library doesn't work well. I got a Bad_Access crash on this line
 `
memcpy(str->enc_xtn_hdr, p->enc_xtn_hdr, p->enc_xtn_hdr_count * sizeof(p->enc_xtn_hdr[0]));
` 
Any help?

**Comment by paulej** [comment]
I've not seen that error when testing on Linux.  When creating the srtp_policy object (second parameter passed into srtp_stream_alloc(), are you zeroing all of the fields?  If not, be sure do do "emset(&policy, 0, sizeof(policy));" before doing anything else with the policy object.

**Comment by sahara108** [comment]
Thank you for your answer. The problem is that I hadn't malloc the policy. On iOS, we need to malloc all nested struct.
