### ISSUE TITLE
srtp_validate_rtp_header doesn't check lengths early enough

### ISSUE THREAD

**Issue by katrielalex** [cisco/libsrtp#181]
(sorry, pressed enter too early!)

[srtp_validate_rtp_header](https://github.com/cisco/libsrtp/blob/master/srtp/srtp.c#L85) reads `hdr->cc` before checking any lengths. If the header is too short (e.g. zero!) then this reads OOB.

This code is reached by calling `srtp_unprotect`, meaning that I think it should be safe to call it on arbitrary packets even if they're silly. If not, is it documented somewhere what assumptions are made by `srtp_unprotect`?

**Comment by paulej** [comment]
Agree.  We could add this right at the start of the function:

``` c
if (*pkt_octet_len < octets_in_rtp_header)
    return srtp_err_status_bad_param;
```

Would that work?

**Comment by katrielalex** [comment]
Yes, I think that would work.
