### ISSUE TITLE
libsrtp 2.0.0 no longer exposes [srtp_]crypto_kernel_replace_cipher_type

### ISSUE THREAD

**Issue by JonathanLennox** [cisco/libsrtp#200]
Rev a9ac898d removed the install of the crypto/include header files into the srtp install directory.

A consequence of this is that [srtp_]crypto_kernel_replace_cipher_type is no longer exposed.  Our system uses this API to replace srtp's crypto implementation with our own, optimized one, so this is blocking us moving up to 2.0.0.

Any thoughts on the best way to fix this?

**Comment by pabuhler** [comment]
It certainly looks like this API was meant to be "public" along with srtp_crypto_kernel_replace_auth_type.
Although I don't know how much of the other functions in the file are meant to be accessed externally.
I see the debug functions have wrappers in srtp.h
We definitely should expose the api again but maybe in a cleaner fashion?
Perhaps in a sub include folder so it is clearly not part of srtp usage api or in a new include file specifically for this api.
Ideally we should only expose what is needed for this api and not the entire krypto kernel but at this point not sure on the amount of work required and if it would be worth it.

This i guess should go in to master, what will be a 2.1.x release at some point.

Other suggestion, will you work on this?

**Comment by jfigus** [comment]
Part of the refactoring for 2.0 was to improve the opacity of the libsrtp data structures.  Prior to 2.0 all those header files were installed into the system, allowing the applications to reach into any private data structure within libsrtp.  With 2.0 we no longer install all all header files, some of which use to contain a mixture of both public and private entry points.  If there's some capability that needs to be exposed through the public API, then we'll need to extend this through one of the existing public header files, or create a new public header file.

IMHO, we should try to isolate the crypto from SRTP as much as possible.  Using OpenSSL for crypto helps achieve this goal.  OpenSSL already has an abstraction layer for using hardware (or kernel) crypto modules.  Why reinvent this wheel in libsrtp?  Another model to consider would be to implement the kernel crypto module as an OpenSSL engine, then configure libsrtp to use OpenSSL for crypto and enable this engine.

**Comment by JonathanLennox** [comment]
I'm happy to work on this -- I can look at reorganizing the header files.

I'd rather not go for the idea of plugging our kernel into OpenSSL -- that's much more heaviweight than our previous solution.
