### ISSUE TITLE
Invalid syntax in util.c

### ISSUE THREAD

**Issue by Globik** [cisco/libsrtp#206]
VC++ 2015 claims on invalid syntax in util.c :+1: 

Line 146

https://github.com/cisco/libsrtp/blob/master/test/util.c
unsigned char sextets[4] = {};
Is empty block scope array c99 or c11 standart? This is in c++ valid, but on c invalid. What is a work around like this?
I do so =>  unsigned char sextets[4] = {0,0,0,0}; Compiled good, but unsure am I, is it correct?

**Comment by traud** [comment]
Thank you for reporting! I am just a external contributor like you, but yes, your solution is [correct…](http://stackoverflow.com/a/201116)

I am going to submit a Pull Request shortly – in your name. Furthermore, I added a compiler flag to GCC so not just the Microsoft guys but the Linux guys see such pitfalls in future as well. Thanks again for reporting and avoiding a headache for your fellows.
