### ISSUE TITLE
libsrtp is not compiling with openssl-1.1.0

### ISSUE THREAD

**Issue by ggarber** [cisco/libsrtp#210]
crypto/include/aes_gcm_ossl.h defines a structure including a EVP_CIPHER_CTX field but EVP_CIPHER_CTX is not public anymore in openssl-1.1.0.  Now EVP_CIPHER_CTX is just forward declared so probably that field should be replaced with a pointer.

**Comment by JonathanLennox** [comment]
So the preferred APIs to use are now EVP_CIPHER_CTX_new and EVP_CIPHER_CTX_free?  Are any other changes needed?

**Comment by ggarber** [comment]
Thats correct.
I didn't see any other error when i tried to compile it but I'm not 100% sure.

**Comment by JonathanLennox** [comment]
@ggarber, can you test my pull request to see if it resolves the problem for you?

**Comment by ggarber** [comment]
The compilation problem is fixed with your branch.  Thx a lot for fixing this so fast!

**Comment by paulej** [comment]
There's a goal of having a 2.1 release by the end of January.  The current code should be stable, as very few PRs have been integrated.  It would be good to have some folks review the code as those PRS are integrated, comment on outstanding PRs, etc.

**Comment by uxmaster** [comment]
OK. I'll give it a try.

**Comment by pabuhler** [comment]
There are currently no plans for a 2.0.x release so closing this as #211 is merged into master and master will be the base of upcoming 2.1 release
