### ISSUE TITLE
Memory Leaks in libsrtp-2.0.0

### ISSUE THREAD

**Issue by nkblaze** [cisco/libsrtp#226]
Hi Folks, I am running Valgrind over mixer module in our project and I am getting some definitely lost bytes in libsrtp code,

Valgrind log report snippet
=======================
==8487== 16 bytes in 1 blocks are definitely lost in loss record 1,261 of 3,965
==8487==    at 0x4027282: malloc (vg_replace_malloc.c:270)
==8487==    by 0x8089A91: srtp_crypto_alloc (alloc.c:73)
==8487==    by 0x8088C07: bitvector_alloc (datatypes.c:363)
==8487==    by 0x8089FBE: srtp_rdbx_init (rdbx.c:192)
==8487==    by 0x8086437: srtp_stream_init (srtp.c:955)
==8487==    by 0x8086B26: srtp_create (srtp.c:2316)

Overall report
===============
==24192== LEAK SUMMARY:
==24192== definitely lost: 1,264 bytes in 7 blocks
==24192== indirectly lost: 0 bytes in 0 blocks
==24192== possibly lost: 164,968,388 bytes in 3,177 blocks
==24192== still reachable: 7,500,659 bytes in 22,297 blocks
==24192== suppressed: 0 bytes in 0 blocks

Need discussion and help over this.

**Comment by paulej** [comment]
Do you have any test code that can be used to reproduce what you see?

**Comment by pabuhler** [comment]
Valgrind has now been added to travis builds and there are no leaks reported. Closing this issues as unreproducible for now. If you have a test case that demonstrates the leak then please re open this issue.
