### ISSUE TITLE
libstrp manual

### ISSUE THREAD

**Issue by carlh54** [cisco/libsrtp#228]
In the current version (2.0) the pdf reference manual was deleted from the release with the reason being that it was out of date. I just read the manual from a previous release and I am wondering which of the information is incorrect.

Is there somewhere where I can up to date information...or do I have to just read the source?

I noticed later that I can generate reference docs which I tried to do. I get this error that I can't resolve (not familiar with text generation tools):

   (/usr/share/texlive/texmf-dist/tex/latex/psnfss/ot1pcr.fd) [1{/var/lib/texmf/fonts/map/pdftex/updmap   /pdftex.map}]
   ! Undefined control sequence.
   l.82 \clearemptydoublepage

Appreciate any help.

/carl

**Comment by thisisG** [comment]
Hey!
Yes the docs are fairly broken as it stands right now. I made a quick attempt at fixing the LaTeX generator but after resolving the missing `\clearemptydoublepage` I hit another error that I was unable to resolve. You are most likely better off reading the code for now as this contains the most up to date info available.
I'll see if I can make a patch to get html docs generated instead!

**Comment by carlh54** [comment]
thanks

**Comment by pabuhler** [comment]
Most of the documentation has been merged in to the README.md file. There is now also generated html documentation, include API documentation in the doc/html folder .
Keep the documentation uptodate will be an ongoing process but this was good start considering where it was.
