### ISSUE TITLE
Clean up the debug api and configure options

### ISSUE THREAD

**Issue by pabuhler** [cisco/libsrtp#230]
The debug options are not complete as it stands today.
The idea would be to create an application call back for debug and to enable an option of debugging to std out based on compile time option.
It should be possible through the api to enable debug level for each module.
By default no debug should be enabled.
There should be no out put to stdout/stderr, all out put should go through the debug api.  
This is a follow on from #183 #48 #110

**Comment by pabuhler** [comment]
After looking through the code I have the following proposal:
- configure option "ENABLE_DEBUGGING" this will enable debugging for all modules regardless of weather they have been enabled though the api, this is very verbose, to be used only when debugging and would be default off.
- configure option "ERR_REPORTING_STDOUT" & "ERR_REPORTING_FILE", this would cause error reporting to go to either stdout or given file name, by default neither would be defined
- new api to set callback that receiver error reports in the application

This simplifies it some what but still offers full flexibility, would be great to get some feedback before finish implementing.

**Comment by paulej** [comment]
Would those be supported with --enable-debugging in "configure"?  Are you proposing to allow the file to be specified or would this be a pre-defined filename?

**Comment by pabuhler** [comment]
The filename should be passed as an argument, I don't see how a default would make sense.

**Comment by pabuhler** [comment]
Closing this now as configure has been updated and a public logging api added.
