### ISSUE TITLE
SIGSEGV in rdb_add_index() when index >= rdb->window_start+256

### ISSUE THREAD

**Issue by timfuze** [cisco/libsrtp#235]
We used srtp version 1.4.2 from "http://srtp.sourceforge.net/srtp.html" and experienced the crash due to SIGSEGV.  After applying the fix per "https://sourceforge.net/p/srtp/mailman/message/2084600/", I don't see the crash anymore.  Just want to make double check here if the issue was addressed as the code here seems hasn't changed.

This is the code that I am using in our product now (/crypto/replay/rdb.c).

```
err_status_t
rdb_add_index(rdb_t *rdb, uint32_t index) {
  int delta;  

  /* here we *assume* that index > rdb->window_start */

  delta = (index - rdb->window_start);    
  if (delta < rdb_bits_in_bitmask) {

    /* if the index is within the window, set the appropriate bit */
    v128_set_bit(&rdb->bitmask, delta);

  } else { 
    
    delta -= rdb_bits_in_bitmask - 1;

    // fix from https://sourceforge.net/p/srtp/mailman/message/2084600/
    if (delta >= rdb_bits_in_bitmask) {
      v128_set_to_zero(&rdb->bitmask);
      rdb->window_start = index - rdb_bits_in_bitmask + 1;
      delta = (index - rdb->window_start);
      v128_set_bit(&rdb->bitmask, rdb_bits_in_bitmask-delta);
    } else {
      /* shift the window forward by delta bits*/
      v128_left_shift(&rdb->bitmask, delta);
      v128_set_bit(&rdb->bitmask, rdb_bits_in_bitmask-delta);
      rdb->window_start += delta;
    }

  }    

  return err_status_ok;
}
```

**Comment by pabuhler** [comment]
Hi, thanks for reporting. You are right, this patch does not seam to be in the master or 1_5_x_throttle.
Are you able to create a pull request? This should be reproducible in a unit test.

**Comment by timfuze** [comment]
Hi @pabuhler 
I tried '/Applications/Xcode.app/Contents/Developer/usr/bin/make runtest' to see if it passes the test but it fails.. hmm, perhaps the logic isn't fitting somehow.

running libsrtp2 test applications...
crypto/test/cipher_driver -v >/dev/null
crypto/test/kernel_driver -v >/dev/null
test/rdbx_driver -v >/dev/null
test/srtp_driver -v >/dev/null
test/roc_driver -v >/dev/null
test/replay_driver -v >/dev/null
make: *** [runtest] Error 1

**Comment by pabuhler** [comment]
Ok. Would need to know which test is failing, do you know which one it is. If you created a pull request I could run the test myself and have a look.

**Comment by timfuze** [comment]
Done. Thanks.

**Comment by pabuhler** [comment]
As I commented in the pull request, it has not been easy to reproduce this based on the explanation given or the old mail thread and the patch it's self causes the replay test to fail so closing this for now. Please reopen if you manage to reproduce with a test or can step wise explain why it should happen based on the code.
