### ISSUE TITLE
Evaluate removing the ISMAcryp options from configure

### ISSUE THREAD

**Issue by pabuhler** [cisco/libsrtp#247]
Discovered while reviewing #238.
Check if this is still needed, seams to be dead and can be removed.

**Comment by paulej** [comment]
The only reference I could find to this was the fact that some very old MPEG code was using the library (https://github.com/stsquad/mpeg4ip/blob/master/lib/ismacryp/README), but even it does not use this switch.  There was some discussion of this years ago: https://sourceforge.net/p/srtp/mailman/message/1810415/.

Projects like https://github.com/gpac/gpac do not rely on libsrtp.  So, it's unclear to me if any out there really do. I doubt it, given the option appears to have no effect.  (Or so it appears to me.)

My guess is that it would be safe to remove it.
