### ISSUE TITLE
Register libsrtp with Coverity Scan

### ISSUE THREAD

**Issue by JonathanLennox** [cisco/libsrtp#251]
Coverity Scan is free source code analysis for open-source tools https://scan.coverity.com/ -- it seems like it'd be a good idea to register LibSRTP with it.

**Comment by pabuhler** [comment]
Seams like a good idea, although a bit of work to set up. Will try to follow up and get this run before the release but no promises.

**Comment by thisisG** [comment]
After discussing this we're mocing this to 2.2 milestone instead of 2.1.

**Comment by pabuhler** [comment]
This is now in and the results are at https://scan.coverity.com/projects/cisco-libsrtp
