### ISSUE TITLE
2.x release does not support --enable-kernel-linux compile option

### ISSUE THREAD

**Issue by ealfan** [cisco/libsrtp#252]
For performance based high throughput systems we create, we use kernel modules that include LibSRTP. Since 2.x does not support --enable-kernel-linux option, we are forced to use 1.5.4 release which is the latest version that supports this option.

We are looking for this support in the future releases.

**Comment by pabuhler** [comment]
Hi @ealfan , I will try to see what status is on this and why it was removed.
You are welcome to submit a patch enabling it.

**Comment by paulej** [comment]
In the mean time, you might want to compare performance of 1.5.4 against the current code in master. Jonathan Lennox made some changes recently that significantly improved performance.

**Comment by thisisG** [comment]
After discussing this we will not look at this actively for the 2.1 release.
A PR is welcomed if someone wants to pick this up!

**Comment by pabuhler** [comment]
Closing this as it is not something we will implement at this time. PR's are welcome if this is something that the community requires.
