### ISSUE TITLE
Standardize indentation style in libsrtp

### ISSUE THREAD

**Issue by JonathanLennox** [cisco/libsrtp#254]
The code indentation style in libsrtp has ended up extremely inconsistent -- two-space, four-space, three-space, leading space on the left before function declarations, etc.  This makes reading it very confusing. I don't much care what form it uses, but it should be consistent.

**Comment by pabuhler** [comment]
Perfect, we have discussed this and decided to wait for after 2.1 release, but it is great that it is now an official issues :)

**Comment by pabuhler** [comment]
Reopen this issues as it was not as easily fixed as I thought. After trying to perform all formatting in on PR it was obvious the reviewing it all was difficult. We will now try to do it in a series of small PR's to make the review easier.
