### ISSUE TITLE
srtcp IV calculation incorrectly masks high bit of sequence number for little-endian platforms.

### ISSUE THREAD

**Issue by mloutris** [cisco/libsrtp#256]
In the function srtp_calc_aead_iv_srtcp(), the most significant bit of the sequence number should be cleared. However, because the byte order is swapped before the bit is cleared, the most significant bit of the least significant byte is cleared instead. The code is currently: 

    in.v32[2] = 0x7FFFFFFF & htonl(seq_num); /* bit 32 is suppose to be zero */

We think that the appropriate change is to apply the mask prior to the conditional byte swap:

    in.v32[2] = htonl((seq_num & 0x7FFFFFFF)); /* bit 32 is suppose to be zero */

**Comment by paulej** [comment]
Agreed, this appears to be an error in the library.

**Comment by pabuhler** [comment]
This will also need to be addressed in the 1.5.x branch so any changes are not incompatible.

**Comment by mloutris** [comment]
This can result in IV calculations that are different from releases without this change,.
It should be explicitly mentioned that this change is not backwardly compatible.

**Comment by pabuhler** [comment]
But at the same time it is broken today for inter op with other implementations (would be nice to confirm that) and between libsrtp deployed on big endian platforms.

**Comment by JonathanLennox** [comment]
Worse than that, doesn't this mean libsrtp repeats IV values every 128 RTCP packets?  I.e. seq_num 0x0000 and seq_num 0x0080 will generate the same IV, on little-endian hosts.

**Comment by pabuhler** [comment]
@JonathanLennox As far as I understand yes, another reason to fix asap.

**Comment by pabuhler** [comment]
Closing this as it has now been fixed in 2.1.0 & 1.6.0
