### ISSUE TITLE
rdb_increment: Possibly incorrect behavior

### ISSUE THREAD

**Issue by Lastique** [cisco/libsrtp#292]
In `rdb_increment` function, crypto/replay/rdb.c, there is this code:

```
  if (rdb->window_start++ > 0x7fffffff)
    return err_status_key_expired;
  return err_status_ok;
```

The counter is post-incremented, which means that when the counter changes from 0x7fffffff to 0x80000000 the function returns `err_status_ok` despite that the overflow has happened. With recent changes to `srtp_calc_aead_iv_srtcp` (see https://github.com/cisco/libsrtp/commit/73e5fcfb64bcebfe9fb88c8031d929162046b555), this would result in returning `err_status_bad_param` because in an invalid `seq_num` is being passed to the function from `srtp_protect_rtcp_aead`. I would expect `err_status_key_expired` to be returned on overflow.

Is this a bug or an intended behavior?

**Comment by paulej** [comment]
Yeah, that looks like a bug. Odd, though, as I think it's been there a long time. Maybe I'm looking at this wrong?

**Comment by pabuhler** [comment]
I agree with @paulej, from what I can tell the previous behavior would have incremented to 0x80000000 and that would have encrypted ok just with an index of 0, which would have been incorrect. Then the next packet would have incremented to 0x80000001 and that would have failed with err_status_key_expired. The new code will now also fail in the 0x80000000 case although the error will be misleading.
@Lastique do you have a fix with a unit test?

**Comment by Lastique** [comment]
I can create a PR with a fix, it's rather trivial. But I don't know how to create a unit test.

**Comment by pabuhler** [comment]
@Lastique  if you make the PR I can try to make a test. Just make PR editable by maintainers.
By the way,  how did you discover this?

**Comment by Lastique** [comment]
https://github.com/cisco/libsrtp/pull/293
https://github.com/cisco/libsrtp/pull/294

> By the way, how did you discover this?

By doing code review of the latest changes. I looked at the related places in the code.

**Comment by pabuhler** [comment]
I add a simple test to #294, if it looks ok then can also added it to the 1.6 patch. The test failed before your change.

Great to see that some others are reviewing the changes, much appreciated!

**Comment by Lastique** [comment]
@pabuhler Thank you. The test looks ok to me.

**Comment by paulej** [comment]
Why do we now have both 293 and 294? Should 293 be closed?

**Comment by Lastique** [comment]
I created PRs for both master and 1.6. You can close https://github.com/cisco/libsrtp/pull/293 if you intend to backport the fix to 1.6 yourself.

**Comment by pabuhler** [comment]
@paulej  could you at least review #294 for master and then after we can decided about #293  in 1.6 branch.

**Comment by paulej** [comment]
Reading my email out of order is creating confusion for me.  I did review that one, right?  Seems like the same code in a larger commit.

**Comment by Lastique** [comment]
I'm not sure what you mean. You did add a thumbs up on my comment with PRs above, if that's what you mean.

**Comment by paulej** [comment]
I guess not.  But I could have sworn I had reviewed this and commented somewhere.

Anyway the code in #293 and #294 looks fine to me.
