### ISSUE TITLE
libsrtp-1.5.4  no modules *.so centos 6

### ISSUE THREAD

**Issue by mariarti** [cisco/libsrtp#298]
Compiled with `./configure CFLAGS=-fPIC --prefix=/usr/lib64`
`make runtest` `crypto test applications passed.` -OK
and after
```
libsrtp-1.5.4]# make install
/usr/bin/install -c -d /usr/lib64/include/srtp
/usr/bin/install -c -d /usr/lib64/lib
cp ./include/*.h /usr/lib64/include/srtp  
cp ./crypto/include/*.h /usr/lib64/include/srtp
if [ "." != "." ]; then cp crypto/include/*.h /usr/lib64/include/srtp; fi
if [ -f libsrtp.a ]; then cp libsrtp.a /usr/lib64/lib/; fi
if [ -f libsrtp.dll.a ]; then cp libsrtp.dll.a /usr/lib64/lib/; fi
if [ -f libsrtp.so.1 ]; then \
		/usr/bin/install -c -d /usr/lib64/lib; \
		cp libsrtp.so.1 /usr/lib64/lib/; \
		ln -sfn libsrtp.so.1 /usr/lib64/lib/libsrtp.so; \
	fi
if [ "libsrtp.pc" != "" ]; then \
		/usr/bin/install -c -d /usr/lib64/lib/pkgconfig; \
		cp ./libsrtp.pc /usr/lib64/lib/pkgconfig/; \
	fi
```
there is nowhere libsrtp.so.1

Instead of this there is `/usr/lib64/lib` folder created by `make install` with `libsrtp.a` (even without libsrtp.so.1)
I expect to see  .so module in /usr/lib64, but no module and strange folder created (other, than pointed in --prefix=/usr/lib64).

same situation with libsrtp-2.0.0  - no modules *.so anywhere.

ps
only  v1.5.2 compiled perfect (without described issues).

**Comment by itollefsen** [comment]
This mostly applies to what's current, not necessarily 1.5.4 (although some if it applies to that as well).

1. If you want to set CFLAGS, do `CFLAGS="<foo>" ./configure`, i.e. set the environment variable before invoking `configure`.

2. Don't explicitly set the -fPIC flag; `configure` will add that flag if it's supported.

3. Setting CFLAGS in the environment also overrides some of the default values. If you just want to add CFLAGS, use EXTRA_CFLAGS (which I believe was added recently).

4. The `--prefix` argument is exactly that, a prefix. It points to the root of the installation, under which installation will make a "bin", "lib", "include", "<whatever>" directories as needed. In your case, you just want to specify "/usr". The library will end up in "/usr/lib". If you want a different directory for the library, as you seem to want, you do `--prefix=/usr --libdir=/usr/lib64`. See `configure --help` for details.

5. By default, only a static library is built. If you also (or only) want the shared library, do `make shared_library` prior to `make install`.

**Comment by mariarti** [comment]
thanks a lot for explanation! it becomes more clear.
I have such situation:
a) for compiling other software module, I need libsrtp. `make install` for that enough. But, when I launch compiled app, it ask for libsrtp.so , so:
b) `make shared_library` help to create libsrtp.so, but in this case compiled .so situated at directory where I compile. So i need manually copy this .so to /usr/lib64 directory. It's look strange for me, because other similar library did it somehow automatically (may be it written in compiling scripts, I don't know) 
Is there a way to make both of this operations more convenient?
Thanks in advance!

**Comment by itollefsen** [comment]
See 4. and 5. in my previous reply. You need to specify `--prefix` and `--libdir` since you want something other than the default. Then you need to do `make shared_library` before you do `make install`.
