### ISSUE TITLE
srtp_remove_stream doesn't remove stream

### ISSUE THREAD

**Issue by Mishamax** [cisco/libsrtp#306]
I add a stream using the following code:

```
srtp_policy_t policy;

memset(&policy, 0, sizeof(policy));
srtp_crypto_policy_set_rtp_default(&policy->rtp);
srtp_crypto_policy_set_rtcp_default(&policy->rtcp);
policy->ssrc.type  = ssrc_specific;
policy->ssrc.value = ssrc;
policy->key        = key;
policy->next       = NULL;

srtp_add_stream(session, &policy);
```

Then I'm trying to remove it:

```
srtp_remove_stream(session, ssrc);
```

and `srtp_remove_stream` returns error code 13 (`srtp_err_status_no_ctx`).

I believe this happens because `srtp_add_stream` converts ssrc to network byte order, but `srtp_remove_stream` does not.
If I manually convert ssrc: `srtp_remove_stream(session, htonl(ssrc));` then it works fine.

libsrtp version 2.0.0.

**Comment by paulej** [comment]
Yes, that's correct that it has to be in network byte order in the "remove" call.  We have this documented in master, but that's not documented in the 2.0 release.

We'd like to have all public APIs use host order, but we're concerned that changing them might cause issues for people upgrading.

**Comment by Mishamax** [comment]
Is master stable enough to use in production?

Because I've also just noticed that `srtp_update_stream` is broken in 2.0 (it doesn't convert byte order between adding and removing the stream), but apparently it's also fixed in master.

**Comment by paulej** [comment]
I believe it is.  We plan to release 2.1 based on what is in master very soon, but just waiting on feedback from people on issues that we think are now resolved.  We've fixed and closed all open items we intended to address in 2.1 and the "issues" section on GitHub lists everything we're not addressing in 2.1, but none are security issues or major bugs.

**Comment by Mishamax** [comment]
Alright, thank you!
Master seems to work fine for me, so I'm closing the bug.
