### ISSUE TITLE
Date for next release

### ISSUE THREAD

**Issue by rdphartel** [cisco/libsrtp#312]
Hi!

Do you have plans to make a release soon? I am asking because I would like to use the code that's on master, but my build system only accepts tagged releases.

Thanks in advance for your answer!

R.

**Comment by pabuhler** [comment]
@rdphartel , if you follow #225  you will see it kind of tracks the release. The plan at the moment is to release in the next two days.

I understand that you may need to use labels/tags but I hope you don't wait for the release before testing that the code works for you?

**Comment by rdphartel** [comment]
No, we don't wait for the release to test.
Thank you for your fast answer!
