### ISSUE TITLE
Delete the VERSION file

### ISSUE THREAD

**Issue by paulej** [cisco/libsrtp#316]
Version 2.1.0 was released today, but only afterward did we note that VERSION file was not updated (so it still shows 2.1.0-pre).  Since the CHANGES file is (necessarily) updated for each release, the VERSION file is redundant.

Can we remove that file or are people relying on its presence for anything?

**Comment by pabuhler** [comment]
If there are no objects to this then lets just do it

**Comment by paulej** [comment]
Go for it
