### ISSUE TITLE
Bad base64 key decoding

### ISSUE THREAD

**Issue by carlh54** [cisco/libsrtp#317]
I hope I can ask this here. If not my apologies in advance.

I'm having trouble decoding the all base64 encoded keys being passed to my device from the remote end.

Despite the actual base64 key having all legit characters, decoding yields non-ascii chars.  I have tried substituting other decoding functions but they all yield garbage. 

Here is an example string that yields garbage:

![image](https://user-images.githubusercontent.com/25154348/27551432-64585c14-5a71-11e7-9414-57e80986adb4.png)

Funny thing is Wireshark doesn't seem to have any problem decoding the base64 string. 

Can anyone suggest what the problem is or what I'm missing?

Thanks
/carl h.

**Comment by paulej** [comment]
The key and salt are binary.  So if you do a base-64 decode, you should end up with a string of octets (in this case) that is 16 octets for the key + 14 octets for the salt (30 octets total) in length.  Looks like Wireshark is just presenting that data in hex form to make is user-friendly.

**Comment by carlh54** [comment]
Thanks for responding. 

So unlike in the other direction where a sequence of random numbers is converted to an ascii string, followed by base64 encoding the string, and then sent to the remote party, in the incoming direction doing a base64 decoding renders the encryption key as hex rather than an ascii string?

**Comment by paulej** [comment]
See the example https://tools.ietf.org/html/rfc4568#section-4.5.  There, the strings "d0RmdmcmVCspeEc3QGZiNWpVLFJhQX1cfHAwJSoj" and "NzB4d1BINUAvLEw6UzF3WSJ+PSdFcGdUJShpX1Zj" are Base-64 encoded binary data.

The "inline" parameter where the key and salt are transmitted is always a base-64 encoding of the binary key and salt values.  What Wireshark is presenting might be different (and I can see how that "Key and Salt" line up there can be confusing).  Is it something you see in the SDP that is confusing you or just Wireshark's representation of the data?

**Comment by carlh54** [comment]
No, what's puzzling me is that my local-to-remote SRTP connection setup by SDP works fine and is decrypting SRTP packets correctly just as I described....binary, to ascii string, to base64. So because of that  I assumed that in the remote-to-local direction of the connection I would have to unwind the base64 string in the SDP the same way....base64, ascii string, binary data. 

Not so?

**Comment by paulej** [comment]
No, the binary key data is not converted to ASCII first before encoding. That just presents confusion, because what is the ASCII conversion?  A hex string?  And would that be upper or lowercase hex?  So, there should be no conversion to anything ASCII, except the base64 encoding step itself.

**Comment by carlh54** [comment]
Thanks Paul.

I'll go back and change things to remove the middle ASCII steps in both
directions. I am curious though as to why it works at all in the
local-to-remote direction.

**Comment by paulej** [comment]
Beats me.  I'm quite surprised, since doing SRTP pretty much requires everything to be perfect.

**Comment by carlh54** [comment]
Thanks Paul. I got it working.

I was using the code in rtpw.c as my template for my implementation. I
guess I got confused with some of the hex/octet conversion utilities used
by the example code. Although I did think to myself at one point that it
was strange doing the extra conversion which turned out to be unnecessary.

**Comment by paulej** [comment]
Excellent. I'll close this issue now.
