### ISSUE TITLE
libsrtp header validation fails when header extensions are present

### ISSUE THREAD

**Issue by tvsriram** [cisco/libsrtp#32]
https://codereview.chromium.org/19678006/

This was a patch submit to chromium. 

Index: srtp/srtp/srtp.c
===================================================================
--- srtp/srtp/srtp.c	(revision 212142)
+++ srtp/srtp/srtp.c	(working copy)
@@ -68,6 +68,7 @@
 #define uint32s_in_rtp_header  3
 #define octets_in_rtcp_header  8
 #define uint32s_in_rtcp_header 2
+#define octets_in_rtp_extn_hdr 4
 
 
 err_status_t
@@ -733,6 +734,12 @@
    if (*pkt_octet_len < octets_in_rtp_header)
      return err_status_bad_param;
 
+   /* Check RTP header length */
+   int rtp_header_len = octets_in_rtp_header + 4 * hdr->cc +
+       (hdr->x == 1) ? octents_in_rtp_extn_hdr : 0;
+   if (*pkt_octet_len < rtp_header_len)
+    return err_status_bad_param;
+
    /*
     * look up ssrc in srtp_stream list, and process the packet with
     * the appropriate stream.  if we haven't seen this stream before,
@@ -977,6 +984,12 @@
   if (*pkt_octet_len < octets_in_rtp_header)
     return err_status_bad_param;
 
+  /* Check RTP header length */
+  int rtp_header_len = octets_in_rtp_header + 4 * hdr->cc +
+      (hdr->x == 1) ? octents_in_rtp_extn_hdr : 0;
+  if (*pkt_octet_len < rtp_header_len)
+   return err_status_bad_param;
+
   /*
    * look up ssrc in srtp_stream list, and process the packet with 
    * the appropriate stream.  if we haven't seen this stream before,

**Comment by jfigus** [comment]
This is resolved by 557a7876b35260817a584434f7bc842f72a106d6
