### ISSUE TITLE
runtest fails if objdir != srcdir

### ISSUE THREAD

**Issue by JonathanLennox** [cisco/libsrtp#321]
If you build libsrtp with objdir != srcdir (e.g. mkdir obj; cd obj; ../configure; make runtest) the tests involving rtpw fail, because words.txt is in $(srcdir)/test/words.txt, but rtpw is executed in $(objdir)/test/.

**Comment by paulej** [comment]
Is this one of those examples where the patient says, "Doctor, it hurts when I do this." To which, the doctor says, "Then don't do that." ?

**Comment by JonathanLennox** [comment]
There are lots of good reasons to build with srcdir != objdir; I do it routinely:

* It lets you keep multiple different architectures / configurations around simultaneously.
* It lets you easily blow away the object files if something goes wrong, without harming your source tree.

My suggestion would be to add a command-line argument to rtpw to override the default dictfile value, and then pass it from the Makefile.

**Comment by pabuhler** [comment]
@JonathanLennox  sounds fine, will you make PR ?
