### ISSUE TITLE
`configure != autoconf(configure.in)` on macOS

### ISSUE THREAD

**Issue by bifurcation** [cisco/libsrtp#326]
While preparing to attempt to make some changes to the build system for libsrtp, I tried to replicate the current autoconfig process before making any changes.  I immediately ran into a few problems:

1. The current `configure.in` file cannot be properly processed by autoconf
2. If you patch `configure.in` so that it works, you don't get the same `configure` file
3. The `configure` file you do get doesn't work

This is with autoconf 2.69, the same version that the current `configure` file claims to have been built with.

```
$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

When that version is run with the current `configure.in` file, it produces the following error:

```
$ autoconf
configure.in:17: error: possibly undefined macro: AM_PROG_AR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

If you make the following change in `configure.in`...

```
-AM_PROG_AR
+m4_ifdef([AM_PROG_AR], [AM_PROG_AR])
```

... then autoconf runs without reporting any errors, but then `./configure` fails.

```
[[ trimmed ]]
checking for usleep... yes
checking for sigaction... yes
checking whether to enable debug logging in all modules... no
./configure: line 4806: PKG_PROG_PKG_CONFIG: command not found
checking whether to leverage OpenSSL crypto... no
./configure: line 4860: syntax error near unexpected token `crypto,'
./configure: line 4860: `     PKG_CHECK_MODULES(crypto, libcrypto >= 1.0.1,'
```

If the process for generating `configure` is something more advanced than running `autoconf`, then we should document that process.

**Comment by itollefsen** [comment]
You do not want to ifdef the use of AM_PROG_AR. See pull request #301 and issue #296.

`pkg-config` is required when regenerating the configure script with autoreconf. It's not required to use the resulting configure script. To be more precises, pkg.m4 is required when regenerating the configure script, since that's where PKG_CHECK_MODULES() et. al. is implemented.

**Comment by pabuhler** [comment]
I agree to adding a section to the README about regenerating the configure script include any requests.
