### ISSUE TITLE
building libsrtp as a shared lib

### ISSUE THREAD

**Issue by klnikita** [cisco/libsrtp#33]
Hello,

I guess that some users want to build libsrtp as a shared library.
Or at least I know that several linux distro are applying a patch like that one : http://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/net-libs/libsrtp/files/libsrtp-1.4.4-shared.patch ,

**Comment by traud** [comment]
For those coming by an Internet search, the name of that target changed since version 1.5 (thanks to issue #100):
./configure --enable-openssl
make **shared_library**
sudo make install
