### ISSUE TITLE
Segmentation fault in srtp_driver

### ISSUE THREAD

**Issue by paulej** [cisco/libsrtp#370]
Code in master produces a segmentation fault running this command:

`test/srtp_driver -t`

The 2.10 stable release does not have this issue.

**Comment by paulej** [comment]
I submitted a pull request for this issue.  We might also want to add this to travis so it might get caught if it happens again.

**Comment by pabuhler** [comment]
We could but it is a timing test not a functional test .... If it is not too cpu intensive we can added. Maybe make a new make target 'runalltests' ?

**Comment by paulej** [comment]
Yeah, I was thinking about that. Fairly CPU intensive test and only addresses the test, not core functionality.  I guess we leave things as they are.
