### ISSUE TITLE
srtp_init failed in FIPS mode with CiscoFOM 6.2

### ISSUE THREAD

**Issue by weilhuan** [cisco/libsrtp#371]
Combine libSRTP and CiscoSSL6.2.83(CiscoFOM 6.2), when calling srtp_init() during startup procedure, it's always failed if FIPS mode is enabled.

**Comment by pabuhler** [comment]
hi @weilhuan if you apply the following patch does it still fail?

```
diff --git a/crypto/cipher/aes_gcm_ossl.c b/crypto/cipher/aes_gcm_ossl.c
index 75519b7..b6aba21 100644
--- a/crypto/cipher/aes_gcm_ossl.c
+++ b/crypto/cipher/aes_gcm_ossl.c
@@ -241,7 +241,7 @@ static srtp_err_status_t srtp_aes_gcm_openssl_set_iv(
                              (void *)iv)) {
         return (srtp_err_status_init_fail);
     }
-    if (!EVP_CIPHER_CTX_ctrl(c->ctx, EVP_CTRL_GCM_IV_GEN, 0, (void *)iv)) {
+    if (!EVP_CIPHER_CTX_ctrl(c->ctx, EVP_CTRL_GCM_IV_GEN, 12, (void *)iv)) {
         return (srtp_err_status_init_fail);
     }
```

**Comment by weilhuan** [comment]
Hi,

I cannot verify the change now since I’m not in office. Besides this change, according to the migration guide of FOM6.2, perhaps we need add *NON_FIPS_ALLOW flag for legacy use such as SHA-1, HMAC.

BTW, can I request fully test with FOM6.2 which has been released quite a while.

Thanks,
Weiliqi



On 1 Nov 2017, at 6:20 PM, Pascal Bühler <notifications@github.com<mailto:notifications@github.com>> wrote:


hi @weilhuan<https://github.com/weilhuan> if you apply the following patch does it still fail?

diff --git a/crypto/cipher/aes_gcm_ossl.c b/crypto/cipher/aes_gcm_ossl.c
index 75519b7..b6aba21 100644
--- a/crypto/cipher/aes_gcm_ossl.c
+++ b/crypto/cipher/aes_gcm_ossl.c
@@ -241,7 +241,7 @@ static srtp_err_status_t srtp_aes_gcm_openssl_set_iv(
                              (void *)iv)) {
         return (srtp_err_status_init_fail);
     }
-    if (!EVP_CIPHER_CTX_ctrl(c->ctx, EVP_CTRL_GCM_IV_GEN, 0, (void *)iv)) {
+    if (!EVP_CIPHER_CTX_ctrl(c->ctx, EVP_CTRL_GCM_IV_GEN, 12, (void *)iv)) {
         return (srtp_err_status_init_fail);
     }

**Comment by weilhuan** [comment]
The patch works fine.

Thanks,
Weiliqi
