### ISSUE TITLE
Is it possible to integrate libsrtp into web servers?

### ISSUE THREAD

**Issue by traw** [cisco/libsrtp#389]
Sorry I'm newbie here,
Is it possible to integrate Libsrtp into web server app specifically [Kore](https://github.com/jorisvink/kore), which can stream live webcam feed from the server to client.
I am confused about how connection can be established between client and sever over secure channel?

**Comment by paulej** [comment]
I'm not familiar with Kore, but if the streaming media is RTP [RFC 3550], then it would be possible to integrate libsrtp with Kor to secure the media flow.  However, my quick initial scan over the readme on GitHub did not hint to streaming media.  To stream media, though, it would certainly be possible to send the media over either an HTTP interface (less ideal) or WebSocket interface (good for buffered media).  Both of those can be secured as they are presently implemented.  You would only need SRTP if you created a separate communication flow between the client and server wherein you transmit RTP packets over UDP.

**Comment by traw** [comment]
yes.. I'm trying make RTP over UDP for latency. But I don't from where to start from, for Media server.

**Comment by paulej** [comment]
Just getting media flowing is one challenge, firewalls are another, and security (focus of libsrtp) is another.  Sounds like you have quite a bit of stuff to learn before you need to worry with libsrtp integration.  I'll close this issue since it does not relate to a real issue with libsrtp, per se.
