### ISSUE TITLE
Split message into packets uisng test rtp

### ISSUE THREAD

**Issue by aristizabal95** [cisco/libsrtp#407]
Hello, I'm pretty new to this type of protocols so bear with me.

I've been trying to use this library to send real time video streams through LAN. So far, I've been able to get a small section of the video frames transmitted using the code inside `test/rtp.c` and modifying `test/rtpw.c` for my own needs. 

Now I need to send the whole image, but the size of the image is larger than that of the message body buffer. I guess I should split my payload into packets that fit inside an rtp message and then rebuild them on the receiver end. Is there any implementation of this? If not, is there any standard I could use for my needs? Thanks.

**Comment by nils-ohlmeier** [comment]
libsrtp will not handle packet fragmentation and reassembly for you. Your regular RTP stack needs to take care of that, before you hand the RTP packets to libsrtp. And yes the standard solution to your big video frame problem is to split the information across several RTP packet and have the receiver re-assemble the original packet after receiving all packets.

**Comment by aristizabal95** [comment]
Thanks for the fast response. Reading through this article (https://notes.shichao.io/tcpv1/ch10/) seems to indicate that IPv4 can be used to handle datagram fragmentation by itself, but I don't know how to use it in thia context. I'll be investigating more, but if you or someone else knows anywhere I can find such implementation and can share any info about this I'd be grateful.

**Comment by aristizabal95** [comment]
Ignore my last comment, jsut read about the problems on using IP for message fragmentation. Researching even further I found out about the H.264 codec which has specifications for Fragmented Units coding/decoding (https://tools.ietf.org/html/rfc6184). I also found in my research this repo https://github.com/cisco/openh264. I must be honest, I've jsut glanced at this repo, not reading through it carefully, but since it comes from the same team as this repo I want to ask a simple straightforward question: Can Openh264 be integrated with libSRTP? And would it fit the purpose for encoding/fragmenting the payload for transfer with (S)RTP?

**Comment by nils-ohlmeier** [comment]
What you are looking for is an RTP protocol stack. Neither libsrtp nor OpenH264 will give you that. libsrtp only takes care of encrypting RTP packets you got out of your RTP stack. OpenH264 takes care of encoding the payload which you feed into your RTP stack, like other video codecs like VP8 or VP9 would as well. But non of this is an libsrtp issue.
