### ISSUE TITLE
SRTP library overflow

### ISSUE THREAD

**Issue by alexandrugrusu** [cisco/libsrtp#431]
Hi,

I wrote a test program which encrypts and decrypts a file.
I figured out that after 4 minutes and 16 seconds, the output signal is not clear anymore. It looks like something overflows.
Is there a structure or some variables which must be reset after a specific number of iterations?

If it is necessary I can attach different screenshots or code snippets.

Regards,
Alex

**Comment by pabuhler** [comment]
Hi, There are some limits regarding key usage and sequnce number wraps but they are very large and should have resulted in an error.  A reproducible test case / code snipit would be the best. Screen shoots will not really help much. If you have a program that is both encrypting and decrypting then that means you have access to both the input data and the decrypted data, can you not do a simple compare to see if the decrypted data always matches the input data? As long as that is ture then the issues does not lie in libsrtp.

**Comment by alexandrugrusu** [comment]
Hi, 
Check the link below to see my test program:
https://gist.github.com/alexandrugrusu/6af4b5d3706ccc83c0a40ca63c8928ae

I'm reading the input data from a file. The data are encrypted and then sent to the decryption routine.
The decrypted data are written in an output file.

**Comment by pabuhler** [comment]
Hi,
I think I see what you are trying to do, in order to see if this is actually a problem in libsrtp instead of your code can you simplify your example to use srtp_protect() & srtp_unprotect(), ie concatenate the input date to a constructed RTP header and pass it to srtp_protect(). Then perform a memcmp() with the intput data and the out put of srtp_unprotect(). If this does not match each time then there is likely an issue.

It might also help to ignore the reading and writing to file while trying to isolate the issue, just generate input data in the test.

**Comment by pabuhler** [comment]
@RusYus  Adding and removing the same streams (SSRC's) will cause synchronization issues between the encryption and decryption contexts. In RTP there is a rollover counter (ROC) that needs to be keep in sync. This effectively counts the number of times that the seq number has wrapped.
If you remove and re add a stream the previous value will be lost. If you know the value of the ROC then you can call srtp_set_stream_roc() after re adding  the stream to prim the decryption context.

Hope that helps.

**Comment by pabuhler** [comment]
@alexandrugrusu have you been able to resolve your issue?

**Comment by alexgrusu** [comment]
@pabuhler sorry for delay, I was not notified regarding the comments.
I solved my issue. I missed to add a function regarding the ROC. It is working fine now.

**Comment by pabuhler** [comment]
@alexandrugrusu , thanks for the update, closing this now.
