### ISSUE TITLE
Fail to decrypt packet using srtp library 1.4.4 and opensll 1.0.2

### ISSUE THREAD

**Issue by getsoubl** [cisco/libsrtp#435]
Hello 
I am working on a project in which try to encrypt/decrypt an rtp payload
We are using DTLS 1.2 /openssl 1.0.2. The encryption is ok but when try to decrypt the package we get the following error
Failed to decrypt RTP Packet from 192.168.180.16:53535 seq:11472 ssrc:(552e607e) errno:172
We use multiplexing 
Thank you
George

**Comment by paulej** [comment]
That's a really old version of code. As a first step, I'd suggest updating it to the latest version.

I don't recall libstrp producing those kinds of error codes. The current code will return error codes as shown here: https://github.com/cisco/libsrtp/blob/master/include/srtp.h#L164

I assume the 172 is a system-specific error. Can you confirm?

**Comment by pabuhler** [comment]
Hi @getsoubl , did you try upgrade to a new libSrtp? I will close this issues now but feel free to reopen if you still have a problem.
