### ISSUE TITLE
if statements in rtp_decoder.c:{372,386,406} check wrong field

### ISSUE THREAD

**Issue by jkougoulos** [cisco/libsrtp#445]
in main() I noticed in the section 
> /* set up the srtp policy and master key */

in lines 372, 386, 406,  if statements use scs.key_size instead of scs.tag_size:
eg.
`   switch (scs.key_size) {`
`                case 128:`
`                    if (scs.key_size == 4) {`

**Comment by paulej** [comment]
That does looks like an error.

**Comment by pabuhler** [comment]
@jkougoulos thanks for reporting this, it should be fixed now.
