### ISSUE TITLE
Unrecognized platform error when datatypes.h is included

### ISSUE THREAD

**Issue by amrithathorath** [cisco/libsrtp#453]
Hi,

I'm trying to generate the SRTP and SRTCP keys for NIST request file. 
I've had to include "crypto/include/datatypes.h" in order to use datatypes like v128_t.
I see the following error:

> /home/libsrtp/libsrtp-master/libsrtp-master/include/../crypto/include/datatypes.h:62:2: error: #error "Platform not recognized"

My platform type is shown below:

> $ uname -ra
> Linux thorath-vm 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

The commands I used to build the lib srtp library are:

- ./configure --enable-debug-logging --enable-log-stdout --enable-openssl --with-openssl-dir=/home/athorath/ssl/
- make

Is there anything else I need to do in oder to get around the platform not recognized error?

Thanks in advance!

**Comment by pabuhler** [comment]
Did you try just a plan "./configure" .  I am not sure why you need to include this file directly but I think it requires include config.h first. Really datatypes.h should have included config.h.

Does it help to include config.h ?

**Comment by amrithathorath** [comment]
Yes, including config.h helped, thank you!
