### ISSUE TITLE
How are calls mapped to OpenSSL

### ISSUE THREAD

**Issue by amrithathorath** [cisco/libsrtp#458]
I'm interested in knowing how key derivation functions work if OpenSSL is enabled with libsrtp.
I see in srtp.c that if OpenSSL and OpenSSL KDF are enabled, then kdf_srtp() is called within srtp_kdf_generate(). But what does kdf_srtp() do? I don't see any implementation of this except for couple of occurrences in "configure" script (but not an implementation).
Can someone please help me understand how the control flows to OpenSSL?

Thanks!!

**Comment by pabuhler** [comment]
hi @amrithathorath , as far as I understand the kdf_srtp() function is not part of standard openssl but is part of some openssl forks that include a kdf_srtp() function inside the FIPS canister. I do not think it is required for FIPS support though as the standard kdf function uses the FIPS compatible EVP openssl functions when libSRTP is built with openssl support. So in general I do not think the config option "--enable-openssl-kdf" is used. Did that make sense?

**Comment by amrithathorath** [comment]
@pabuhler : Thanks for your response.
I'm using OpenSSL-1.0.2p and OpenSSL-fips-2.0.16 and I've downloaded these from official [OpenSSL ](https://www.openssl.org/source/old/)website and I don't see kdf_srtp() function.
I'm particularly interested in seeing how the KDF part is done, the entire process including all the EVP calls used. I don't see any of these in libsrtp code, so can you please point me to it.

**Comment by pabuhler** [comment]
Like I said the kdf_srtp() function is not in the official/standard openssl code. The support for the openssl kdf_srtp() call from libSRTP was added to support some variants/forks of openssl that do include a kdf_srtp() function. libSRTP does include its own KDF function, if you look in srtp.c there are two version of srtp_kdf_generate(), one that uses kdf_srtp() if configured to do so and the other that uses libSRTP internal AES ICM cipher interface. In the case that libSRTP uses openssl for encryption this interface is implemented in aes_icm_ossl.c .

**Comment by amrithathorath** [comment]
Thanks for the comment, that was helpful.
