### ISSUE TITLE
Please provide to vcpkg

### ISSUE THREAD

**Issue by bleissem** [cisco/libsrtp#460]
Dear Sir or Madam,
there is a Microsoft package manager  for C/C++ projects .
https://github.com/microsoft/vcpkg
It would be nice that you also publish releases for windows as a vcpkg package.
Thanks in advance.
Reagards
Alex B.

**Comment by pabuhler** [comment]
Hi @bleissem, I am unsure if vcpkg is for binary or source distribution. Currently the only official distributions are the source release on github. Any binary distributions are provided by others.
You are free to submit what ever is needed to support vcpkg and we can help if there are issues but we can not commit to maintenance / support.

**Comment by pabuhler** [comment]
Will close for now, but please reopen if you think strongly about adding vcpkg support. In which case please come with a PR.
