### ISSUE TITLE
question about crypto keys

### ISSUE THREAD

**Issue by bleissem** [cisco/libsrtp#461]
Hello, 
I'm currently using .Net to decrypt messages reveived with 
AES_CM_128_HMAC_SHA1_32
I want to ask if the function
srtp_unprotect
does meet AES standard so that instead of writing using the libsrtp the .Net class AES can be used instead ? 
https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.aes?view=netcore-2.2

**Comment by paulej** [comment]
Being AES compliant by itself is not sufficient to answer your question.  The AES algorithm is standard and libsrtp can use the one built in internally, the implementation in OpenSSL, etc. They're all compatible.  However, encryption is only one part of decrypting an SRTP packet.  AES works with a number of different block cipher modes (see https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation).  What SRTP specifies is a "counter mode", but the counter is very rigidly specified in the specification.  There is also the initialization vector that must be constructed per the SRTP spec.  Given that, any AES implementation should work to perform the actual cipher block decryption step.  That said, I do not know what that particular API from Microsoft is doing.  But, I suspect if you handle the IV and CTR parts yourself, you can use the ECB mode with that API to actually do the decryption step.  That does appear to be a valid mode (https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.ciphermode?view=netcore-2.2).  Alas, I've never looked at those APIs, so I can't really provide any guidance.  That's jsut my initial thought as to how I'd do it after looking at that for 10 seconds. :)

**Comment by bleissem** [comment]
Hello @paulej ,
I've been off a few weeks, so I could not reply sooner. 
Thanks for your real quick answer. I have another AES related question.
As in
https://tools.ietf.org/html/rfc4568#section-6.1
eg.
a=crypto:1 AES_CM_128_HMAC_SHA1_32 inline:u/uhRjLE3pkM0qunRqcYqF1G1zxnx3DlOgWg5Ffi
there is a master key and a salt value that is being send.
I assume, that the master key value is related to the key value of an AES encryption.
But how is the IV value of an AES algorithm related to the salt value ?

Regards
Alex B.

**Comment by paulej** [comment]
Alex,

I apologize that I neglected to reply to this.  I completely overlooked it.

By now, you've probably figured it out.  Either way, the salt is used with the master key to create all of the actual keys.  See https://tools.ietf.org/html/rfc3711#section-4.3 for a description of the key derivation logic followed by SRTP.  You'll see in that section that there are several keys derived from the master key and master salt named k_e, k_a, k_s.  For SRTCP, there are also keys derived as explained in 4.3.2.

Paul

**Comment by bleissem** [comment]
Hi @paulej,
yes I already figured out how those values are related to each other. 
Anyway thanks for your help. I should have closed this issue earlier. 
Regards
Alex B.
