### ISSUE TITLE
How to compile with AES-GCM support?

### ISSUE THREAD

**Issue by sommerper** [cisco/libsrtp#464]
In order to get meetecho-janus (https://github.com/meetecho/janus-gateway) to work securely I need to compile libsrtp with support for AES-GCM but I'm not sure how to do that.
I installed libsrtp version 2.1 and it seems it doesn't include it. At least not according to Janus as you can see in the startup info below.

I apologise if this is not the right place to ask but I already tried on the Janus forum and am not getting any replies.

Thanks

```
~/janus-gateway$ sudo ./janus -c /etc/letsencrypt/live/asd.com/fullchain.pem -k /etc/letsencrypt/live/asd.com/privkey.pem

Janus commit: eb703e1a53360a7f967e4d969dec957a7249e134
Compiled on:  Sun Sep  1 00:23:44 UTC 2019

---------------------------------------------------
  Starting Meetecho Janus (WebRTC Server) v0.7.4
---------------------------------------------------

Checking command line arguments...
Debug/log level is 4
Debug/log timestamps are disabled
Debug/log colors are enabled
Adding 'vmnet' to the ICE ignore list...
Using xxx.xxx.xxx.xxx as local IP...
[WARN] Token based authentication disabled
Initializing recorder code
Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, half-trickle, IPv6 support disabled)
TURN REST API backend: (disabled)
Crypto: OpenSSL >= 1.1.0
[WARN] The libsrtp installation does not support AES-GCM profiles
```

**Comment by fancycode** [comment]
You need to build libsrtp with either OpenSSL or NSS to get support for the AES-GCM profiles.

**Comment by sommerper** [comment]
Thanks!

**Comment by marc0s** [comment]
@sommerper did you manage to solve it?  I have the same problem, using debian buster package for `libsrtp2-1 2.2.0-1 ` and `openssl 1.1.1c-1` and got the same warning. Thanks :)
