### ISSUE TITLE
Can't install on CentOS 8, libcrypto

### ISSUE THREAD

**Issue by anutator** [cisco/libsrtp#468]
Errors:
```
configure: error: Package requirements (libcrypto >= 1.0.1) were not met:

Package 'libcrypto', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables crypto_CFLAGS
and crypto_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details
```
But I have libcrypto:
`-rwxr-xr-x. 1 root root 3290360 мая 11 04:57 /lib64/libcrypto.so.1.1.1`

**Comment by pabuhler** [comment]
Hi, I am not familiar with CentOS but I cant see why it should be different.
Are you building from a git clone or package?
Do you have the openssl development package installed?
If you provide the config.log it might contain something useful. You could also try with cmake and see if that works better.

**Comment by pabuhler** [comment]
Do you still have issues building/installing, you can see examples on building on different platforms with and without openssl in the .travis.yml file. If you find problems with the libsrtp build files then please reopen this issue and provide enough information that it can be easily reproduced.

**Comment by bibaodi** [comment]
I think the dev package shoud be installed.
```
apt install libgcrypt20-dev
```
just FYI.
