### ISSUE TITLE
Please clarify license of RFC text

### ISSUE THREAD

**Issue by bastien-roucaries** [cisco/libsrtp#47]
Hi,

What is the license of the RFC file ? 

I suppose it is according to  Trust Legal Provisions (TLP) 3.C distribbuting here means that you have relicenced your own work as BSD ?

care to confirm ?

Bastien

**Comment by jonassmedegaard** [comment]
RFCs are commonly licensed incompatibly with some interpretations of "Free" - in particular (for me and Bastien, both Debian developers) the Debian Free Software Guidelines also used as basis for the definition of "Open Source".

Therefore not only the licensing of RFC 3711 but also that of draft 2026 is valuable to get clarified, and if not Free then please consider not shipping it with srtp to ease redistribution e.g. by Debian.

Hope that helps,

 - Jonas

**Comment by jfigus** [comment]
Sorry, I'm slow on the uptake.  Are you simply proposing that we remove doc/rfc3711.txt from the repo?

**Comment by jonassmedegaard** [comment]
Quoting John Foley (2015-06-02 20:07:53)
> Sorry, I'm slow on the uptake. Are you simply proposing that we remove 
> doc/ rfc3711.txt from the repo?

Either of these:

 a) Remove doc/rfc3711.txt and doc/draft-irtf-cfrg-icm-00.txt

 b) Clarify how those files are Free

While at it, you might also consider removing the releases directory, 
which looks like obsolete cruft to me.


Thanks for considering,

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by jfigus** [comment]
I'll remove the IETF docs.  Not being a lawyer, I couldn't begin to comment on the legality of keeping these files in the repo.

**Comment by jfigus** [comment]
This is resolve by a5de83b95e1e39d6c19c23b13212294cad18d380
