### ISSUE TITLE
autoconf cross-compile fails in 2.3.0 with PR #414

### ISSUE THREAD

**Issue by abelbeck** [cisco/libsrtp#479]
Using release 2.3.0 containing the PR #414 change, the autoconf test hard fails when cross compiling ...
```
checking if OPENSSL_cleanse is broken... configure: error: in `/home/dev/astlinux/trunk/output/build/libsrtp-2.3.0':
configure: error: cannot run test program while cross compiling
See `config.log' for more details
```
There is no assumed case while cross compiling.

**Comment by disa6302** [comment]
Is this going to be merged in anytime soon? 
I am running into this issue when I run configure on ARM platform.

**Comment by disa6302** [comment]
Also, if this is not going to be merged anytime soon, is there a workaround?

**Comment by abelbeck** [comment]
@disa6302 : The solution is to revert PR #414 ... this issue documents the problem.

**Comment by disa6302** [comment]
Got it. Would the revert be made part of the release anytime soon?

**Comment by abelbeck** [comment]
I do not have any permissions here, just a project that uses it, but it seems to me the OpenSSL version the PR #414 fixes is deprecated and no longer supported. So rather than fixing #414 it may be best to revert it at this point in time.

**Comment by pabuhler** [comment]
Hi, sorry for not following up sooner, will review again now an give some feedback.

**Comment by pabuhler** [comment]
This should now be merged. reopen if you still have problems
