### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [cisco/libsrtp#480]
Memory is allocated

https://github.com/cisco/libsrtp/blob/3ef1d8f323a6d2679a4754a543f232357eb0f102/test/rtp_decoder.c#L272

but at the end of function，never free it

**Comment by pabuhler** [comment]
Hi, thanks

I think the answer here is that the input_key should never be allocated, it should either point at the key argument from "-k" or be null and generate an error if not set. What do you think?

**Comment by QiAnXinCodeSafe** [comment]
agree
