### ISSUE TITLE
Sample application for video streaming

### ISSUE THREAD

**Issue by santhoshht** [cisco/libsrtp#485]
Hello,

I'm a newbie on video streaming. I searched sample implementation in /test folder. 

My requirement is to securely stream video frames dynamically. Could you please provide any sample application which uses the libsrtp protocol used.

Thanks in advance.

**Comment by pabuhler** [comment]
Hi, libsrtp is a library that provides encryption for RTP packets,  capturing media and encoding into RTP or streaming RTP packets over a network is out of the scope of this library.
