### ISSUE TITLE
start fail(crash) when use openssl1.1.1e

### ISSUE THREAD

**Issue by situnan** [cisco/libsrtp#488]
./configure --enable-openssl --with-openssl-dir=/usr/local/ssl

(gdb) bt
#0  0x00007ffff68c9859 in EVP_MD_CTX_clear_flags (ctx=0x0, flags=2) at crypto/evp/evp_lib.c:514
#1  0x00007ffff688fecf in EVP_DigestInit_ex (ctx=0x0, type=0x7ffff6d79e40 <sha1_md>, impl=0x0) at crypto/evp/digest.c:68
#2  0x00007ffff68e086e in HMAC_Init_ex (ctx=0x612000c89460, key=0x7fffeb9b63e0 <srtp_hmac_test_case_0_key>, len=20, md=0x7ffff6d79e40 <sha1_md>, impl=0x0) at crypto/hmac/hmac.c:70
#3  0x00007fffeb9aca5a in srtp_hmac_init (statev=0x612000c89460, key=0x7fffeb9b63e0 <srtp_hmac_test_case_0_key> '\v' <repeats 20 times>, key_len=20) at crypto/hash/hmac_ossl.c:157
#4  0x00007fffeb9abde7 in srtp_auth_type_test (at=0x7fffebbbac80 <srtp_hmac>, test_data=0x7fffebbbac00 <srtp_hmac_test_case_0>) at crypto/hash/auth.c:122
#5  0x00007fffeb9ac6c3 in srtp_auth_type_self_test (at=0x7fffebbbac80 <srtp_hmac>) at crypto/hash/auth.c:188
#6  0x00007fffeb9b0bc8 in srtp_crypto_kernel_do_load_auth_type (new_at=0x7fffebbbac80 <srtp_hmac>, id=3, replace=0) at crypto/kernel/crypto_kernel.c:390
#7  0x00007fffeb9b0e42 in srtp_crypto_kernel_load_auth_type (new_at=0x7fffebbbac80 <srtp_hmac>, id=3) at crypto/kernel/crypto_kernel.c:437
#8  0x00007fffeb9b00d3 in srtp_crypto_kernel_init () at crypto/kernel/crypto_kernel.c:193
#9  0x00007fffeb99c55b in srtp_init () at srtp/srtp.c:2693

**Comment by situnan** [comment]
use：libsrtp-2.1.0

**Comment by pabuhler** [comment]
Is this still reproduce able for you when building from master and using latest openssl1.1 ?

**Comment by pabuhler** [comment]
Close this as there has been no follow up, please reopen with more details if the problem still exists.
