### ISSUE TITLE
question about the library of ssl

### ISSUE THREAD

**Issue by ycyang1229** [cisco/libsrtp#494]
I am new in this project.  I wonder is it possible to change the library of ssl from openssl to mbedtls? If I want to do this change, what obstacles will I face?

**Comment by nils-ohlmeier** [comment]
If you take a look here https://github.com/cisco/libsrtp/tree/master/crypto/cipher you will find different cipher implementations for OpenSSL, the files ending in *_ossl.*, and for NSS, ending in *_nss.*. That should give you an idea how to add support for another crypto library.

**Comment by ycyang1229** [comment]
Cool. Let me dive it. Thanks!

**Comment by ycyang1229** [comment]
@nils-ohlmeier Hey, I created one pull req for this change. If you have the interest in it, please take a look. thanks.
