### ISSUE TITLE
Premature re-keying

### ISSUE THREAD

**Issue by Absatt** [cisco/libsrtp#509]
In aes_icm.c line 304, **_bytes_to_encr_** counts in bytes and the **_counter_** counts in 16 bytes (AES block size). The effect of this bug is that the encryption layer prematurely refuses to encrypt further data and requests _**re-keying**_. I have not investigated the issue thoroughly, but there could be other effects since the maximum strp packet size is 2^20 which is greater than the max counter 2^16. A potential fix would be dividing _**bytes_to_encr**_ by 16 and rounding up.

**Comment by pabuhler** [comment]
Thanks for reporting, did you look in to this further ? I will try to follow up now.
