### ISSUE TITLE
Any new release (2.4.0) soon ?

### ISSUE THREAD

**Issue by ydroneaud** [cisco/libsrtp#522]

**Comment by pabuhler** [comment]
Hi, we will likely have a new 2.4 release in the next couple of months, do you have anything in particular you are waiting for?

**Comment by ydroneaud** [comment]
A working ./configure :) Thanks

**Comment by pabuhler** [comment]
@ydroneaud  does the the configure in master work for you, or are you missing more?

**Comment by ydroneaud** [comment]
It works for me

**Comment by kloczek** [comment]
+1

**Comment by paulej** [comment]
Do we want ./configure anymore or just a cmake config? Personally, I'd like to get rid of the ./configure version and work to create a good, readable cmake config since, from that, one can build on a plurality of platforms more easily.

**Comment by kloczek** [comment]
ac/am/lt still works as it should so to be honest (Just testted with autoconf 2.71) I don't see any reasons to waste time to replace that by cmake.
So to be honest I have no idea what you mean mentioning "good, readable" :)
ac/am/lt works on everything when cmake still have sometimes some  issues ..

**Comment by paulej** [comment]
It's definitely not a waste of time. I think most people building on Windows are either using cmake or are manually creating Visual Studio project files. However, in the two most recent projects I've worked with (one Windows and one Linux), cmake was used. Cmake is there already due to demand for it, but it needs some improvement.  The challenge we have now is we must support two build methods.

**Comment by kloczek** [comment]
What is the problem with ac/am/libtool and Windows?

**Comment by paulej** [comment]
Sorry for the belated reply.  Other messages got piled on top and I'm just digging my way out.

I think the answer is that that's a rare thing to use on Windows.  For Windows, most people create Visual Studio project files or create Makefiles for Microsoft's make by hand; I've done both.  However, cmake is gaining popularity to the point that it's supported directly from Visual Studio now, or it can be used to generate visual studio project files.

**Comment by tp-m** [comment]
Just on a sidenote, the Meson build system build is also used on Windows (and elsewhere) by stacks such as e.g. GStreamer, mostly in combination with the `ninja` backend (but there are other backends too of course). Depends on the wider ecosystem of one's project.

**Comment by kloczek** [comment]
Generally +1

> A working ./configure :) Thanks

Here is the patch which I'm using to be able use libsrtp with autoconf 2.71.
Itf that patch will be approved I'll make PR
```patch
--- a/configure.ac~     2021-03-27 22:36:53.986620546 +0000
+++ b/configure.ac      2021-03-27 22:48:54.382421014 +0000
@@ -15,8 +15,7 @@
 AC_ARG_VAR(
   [EXTRA_CFLAGS],
   [C compiler flags appended to the regular C compiler flags instead of overriding them])
-AM_PROG_AR
-AC_PROG_RANLIB
+LT_INIT
 AC_PROG_INSTALL
 AC_PROG_SED

@@ -144,7 +143,8 @@
 CFLAGS="$supported_cflags"

 dnl Checks for header files.
-AC_HEADER_STDC
+AC_CHECK_INCLUDES_DEFAULT
+
 AC_CHECK_HEADERS(
     [unistd.h byteswap.h stdint.h sys/uio.h inttypes.h sys/types.h machine/types.h sys/int_types.h],
     [], [], [AC_INCLUDES_DEFAULT])
@@ -417,7 +417,7 @@
     AC_MSG_RESULT([$EXTRA_CFLAGS])],
    [AC_MSG_RESULT(no)])

-AC_CONFIG_HEADER([crypto/include/config.h:config_in.h])
+AC_CONFIG_HEADERS([crypto/include/config.h:config_in.h])

 AC_CONFIG_FILES([Makefile crypto/Makefile doc/Makefile fuzzer/Makefile libsrtp2.pc])
 AC_OUTPUT
```

**Comment by kleener** [comment]
Apart from configure and cmake, it would be good to have a new release, as all distributions only provide version 2.3.
For example:
https://pkgs.alpinelinux.org/packages?name=libsrtp-dev&branch=edge
https://packages.ubuntu.com/hirsute/libsrtp2-1

**Comment by pabuhler** [comment]
Close as 2.4.0 has now been released.

@kloczek If you are interested in getting that patch in then I would suggest a PR so it can be properly evaluated/tested.
