### ISSUE TITLE
Test failures with NSS 3.60.1

### ISSUE THREAD

**Issue by bifurcation** [cisco/libsrtp#523]
@pabuhler reports that after upgrading to NSS 3.60.1, tests exercising AES-GCM with NSS fail.  Creating this bug to capture details.

cc @martinthomson

**Comment by pabuhler** [comment]
The PK11_Encrypt function is returning -1 when running the cipher self test, will investigate some more.

**Comment by martinthomson** [comment]
Opened https://bugzilla.mozilla.org/show_bug.cgi?id=1689209

**Comment by pabuhler** [comment]
There was an API change in NSS that causes this, https://bugzilla.mozilla.org/show_bug.cgi?id=1637488#c3 has details and possible solutions. PR is coming.

**Comment by martinthomson** [comment]
Happy to provide review if you decide to use the new parameter structs.

**Comment by pabuhler** [comment]
@martinthomson thanks for the quick help yesterday. I have done the simplest fix for now and you are welcome to review that.
As I understood the other options introduce nss version requirements. As I do not know enough about what versions of nss are in use and there does not seam to be anything to gain by adding these version requirements I have chosen to go with this fix for now.
If you have a better option then we can look at doing that.

**Comment by martinthomson** [comment]
Kevin was the one who managed to remember the change :)  Happy to facilitate of course.
