### ISSUE TITLE
rename master branch to main 

### ISSUE THREAD

**Issue by fluffy** [cisco/libsrtp#526]

**Comment by nils-ohlmeier** [comment]
@fluffy I'm assuming you meant "rename master to main" :-)

**Comment by pabuhler** [comment]
Have been thinking about this lately and agree. Am trying to get as far as making a 2.4.0 release in the next month, maybe this can happen just after that ?

**Comment by fluffy** [comment]
I don't see any rush on this and we should do it when they are not a ton of outstanding PRs, thought it is pretty easy to deal with remapping them. Perhaps after the release would be a good time.

**Comment by dpocock** [comment]
Some people feel that changes like this are a distraction from addressing the real issues that are being hinted at.

**Comment by fluffy** [comment]
Done
