### ISSUE TITLE
configure fails when cross-compiling

### ISSUE THREAD

**Issue by Saur2000** [cisco/libsrtp#528]
The commit ec465b8f (Detect and handle broken "OPENSSL_cleanse".) introduced the use of the AC_RUN_IFELSE macro in configure.ac. When cross-compiling, `configure --enable-openssl` now fails with:

> checking if OPENSSL_cleanse is broken... configure: error: in `...':
> configure: error: cannot run test program while cross compiling

As far as I can tell, there is no way to tell configure, using some argument or though the cache, what value it should use for openssl_cleanse_broken to avoid having to run a program, which will not work when cross-compiling.

**Comment by pabuhler** [comment]
@Saur2000  what version are you using ?  Does the commit f379f4841228ee82932b56509e73adaf6552ce6e not fix this for you ?

**Comment by Saur2000** [comment]
I was not aware of that commit as we are using 2.3.0. 
I have verified that it solves our problem by backporting it.
