### ISSUE TITLE
Does '--enable-shared' support in configure 

### ISSUE THREAD

**Issue by xiaolihu** [cisco/libsrtp#533]
I tried add this config options but seems libsrtp.so not generated. by default it is libsrtp2.a ?

Thanks.
Xiaolin

**Comment by pabuhler** [comment]
I think if you see the out put when running with --enabled-shared you would see 
`configure: WARNING: unrecognized options: --enable-shared`
To build a shared library do the following
```
./configure
make shared_library
```

**Comment by xiaolihu** [comment]
Thank you @pabuhler.   ( I overlooked the warning message in config.log)
