### ISSUE TITLE
ciscossl7 support for libsrtp

### ISSUE THREAD

**Issue by vanand123** [cisco/libsrtp#545]
I have below query regarding libsrtp:
Is libsrtp 2.3.0 Ciscossl7 compliant ? If no, Is there any plan to make libsrtp ciscossl7 compliant ?

**Comment by paulej** [comment]
That's a question better asked internally at Cisco, not on a public forum. I'm not sure what you mean by "compliant". If you mean "compatible" (e.g., using libsrtp with ciscossl to handle the AES GCM, for example), they should work fine together. If you're having trouble, find me on WebEx Teams and we can get it figured out.
