### ISSUE TITLE
cross compilation not working on commit ID:    bd0f27ec0e299ad101a396dde3f7c90d48efc8fc

### ISSUE THREAD

**Issue by shiv50084** [cisco/libsrtp#557]
Its showing a compilation error. When cross compiling for mips arch its showing an cmake error:

------------------------------------------

CMake Error at CMakeLists.txt:245 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

-- Configuring incomplete, errors occurred!
See also "/home/shiv/project/kent/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libsrtp/build/src/project_libsrtp-build/CMakeFiles/CMakeOutput.log".
See also "/home/shiv/project/kent/amazon-kinesis-video-streams-webrtc-sdk-c/open-source/libsrtp/build/src/project_libsrtp-build/CMakeFiles/CMakeError.log".
CMakeFiles/project_libsrtp.dir/build.make:106: recipe for target 'build/src/project_libsrtp-stamp/project_libsrtp-configure' failed
make[2]: *** [build/src/project_libsrtp-stamp/project_libsrtp-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/project_libsrtp.dir/all' failed
Makefile:83: recipe for target 'all' failed
make[1]: *** [CMakeFiles/project_libsrtp.dir/all] Error 2
make: *** [all] Error 2
CMake Error at CMake/Utilities.cmake:72 (message):
  CMake step for libsrtp failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:131 (build_dependency)

-- Configuring incomplete, errors occurred!
See also "/home/shiv/project/kent/amazon-kinesis-video-streams-webrtc-sdk-c/mips_build/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.

-------------------------------------------------------------

**Comment by pabuhler** [comment]
@shiv50084  I am closes this for now as it has been awhile.
Please reopen if there is some thing that can be done.
