### ISSUE TITLE
Unexecuted lines in the `update_template_streams` function

### ISSUE THREAD

**Issue by saygins** [cisco/libsrtp#568]
Hi,
`new_stream_list variable` is defined at the beginning of the the `update_template_streams` function. 

`srtp_stream_t new_stream_list = NULL;`

It is not used until  the while loop

```
if (status) {
    /* free new allocations */
    while (new_stream_list != NULL) {
        srtp_stream_t next = new_stream_list->next;
        srtp_stream_dealloc(new_stream_list, new_stream_template);
        new_stream_list = next;
    }
    srtp_stream_dealloc(new_stream_template, NULL);
    return status;
}
```

So the condition will be always false. I think it was forgotten to assign a value to this variable before the while loop.

**Comment by pabuhler** [comment]
but this is inside a for (;;) {}  loop, so it wont be set the first time, but can be set the second time around. Or does that not make sense ?

**Comment by saygins** [comment]
sorry, I didn't see, thanks.
