### ISSUE TITLE
Request link to wolfssl

### ISSUE THREAD

**Issue by voztovoice** [cisco/libsrtp#584]
Hello,

would be a great change link libsrtp to wolfssl library:

https://www.wolfssl.com/

This library is very lightweight and created for RTOS environments (Real Time Operating Systems)

Support TLS 1.3 and the most moderns cipher-suite

Thank you

Regards

**Comment by pabuhler** [comment]
@voztovoice   PR's are welcome.  Unless there is an over welling ask for this I do not think the libsrtp team we will provide the port.

**Comment by voztovoice** [comment]
Thank you for your answer. Regards

**Comment by pabuhler** [comment]
Closing now as it is old, note this is not a rejection of wolfssl so if a PR comes we will look at it.
