### ISSUE TITLE
Is it possible to use the library just to secure an rtp/rtcp packet without using the library's session?

### ISSUE THREAD

**Issue by hgulamabbass** [cisco/libsrtp#587]
Hi There, I am trying to write a C# application to use the SRTP library. Is it possible to call the **srtp_protect(...)** or equivalent without having a session setup? 

I would like to get the secure packet and send it down the existing infrastructure of sending packets written in C#. i.e. I want to use srtp library just to secure the packet and unwrap the incoming packet?

**Comment by paulej** [comment]
It is necessary to maintain state associated with each packet to be encrypted or decrypted, including keys, ROC, etc.  Thus, the session setup (and associated data) is necessary.

**Comment by pabuhler** [comment]
@hgulamabbass   I am closing this as the answer is no, as Paul mentioned.
