### ISSUE TITLE
Can we update the project  to adapte riscv platform

### ISSUE THREAD

**Issue by alongL** [cisco/libsrtp#592]
When I compile this project in riscv-64 ubuntu, I must use command like this, or the configure will show error
```
./configure --build=riscv64
```
error:
```
config.guess timestamp = 2016-05-15

uname -m = riscv64
uname -r = 4.15.0-76-generic
uname -s = Linux
uname -v = #86-Ubuntu SMP Fri Jan 17 17:25:58 UTC 2020

/usr/bin/uname -p = riscv64
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              = riscv64
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = riscv64
UNAME_RELEASE = 4.15.0-76-generic
UNAME_SYSTEM  = Linux
UNAME_VERSION = #86-Ubuntu SMP Fri Jan 17 17:25:58 UTC 2020
configure: error: cannot guess build type; you must specify one

```

shell we update the  posix/config.guess and posix/config.sub to support riscv platform?
more info see this link.
https://github.com/nzbget/nzbget/issues/755#issuecomment-850878871

**Comment by paulej** [comment]
Anyone using this in practice, or is this an academic exercise?

**Comment by alongL** [comment]
fedora use this for riscv version.   
https://dl02.fedoraproject.org/pub/alt/risc-v/logs/libsrtp-1.5.4-3.fc25.src.rpm/build.log 
the command they used:
```
./configure --build=riscv64-redhat-linux-gnu --host=riscv64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info
```

**Comment by pabuhler** [comment]
Quick question why do you still build a 1.5 version ? Please update to 1.6 or even better drop 1.x and include only 2.4 .

Currently there is no one with a lot of auto tools experiencing on the team so the best would be if you create a pull request and as long as it does not break existing builds it should be OK.
