### ISSUE TITLE
Cross-compilation for iOS

### ISSUE THREAD

**Issue by mehmetcy84** [cisco/libsrtp#613]
Is there a tutorial/guideline/readme documentation to cross-compile libsrtp for iOS (e.g. iphone)?

**Comment by pabuhler** [comment]
@mehmetcy84 , Hi sorry for the late reply, there are examples of using cmake & meson in https://github.com/cisco/libsrtp/blob/main/.travis.yml from the previous CI solution, these are currently not run but should still be valid. Maybe I will look at adding io & android to current CI solution.
