### ISSUE TITLE
New release would be appreciated

### ISSUE THREAD

**Issue by nirbheek** [cisco/libsrtp#633]
Hi! There have been a lot of fixes (particularly on the meson side) that would be nice to have in a release, and the last one was over a year ago. Can we have a release?

**Comment by pabuhler** [comment]
working on it ... hopefully in the not so distant future.

**Comment by pabuhler** [comment]
@nirbheek done! and thanks for the prod, it is some times needed.

**Comment by nirbheek** [comment]
Thanks for the release!
