### ISSUE TITLE
Usecase Question about libsrtp

### ISSUE THREAD

**Issue by zhpixel517** [cisco/libsrtp#634]
Hi all,
I'm working on a project that involves peer to peer audio streaming between smartphones. The app is sort of like a walkie-talkie, where one user speaks into their smartphone and their voice is immediately sent to another smartphone. I've been looking at a lot of possible implementations for this project, and I was wondering if libsrtp could stream audio samples with low latency between mobile devices. My first implementation struggled with latency because the audio was sent over the internet with a certain plugin I was using. I'm hoping that using RTP instead will be much better - as the latency for my app needs to be pretty fast because of the use case. Could I use this plugin for this kind of project? Is RTP even the right approach to take?

**Comment by pabuhler** [comment]
Hi @zhpixel517 ,  RTP is a good protocol for what you describe, but the libSRTP project is about securing / encrypting and existing RTP stream. It does not include code to generate RTP or to send / revive RTP over the network. Hope this clears some things up for you.
